### ISSUE TITLE
Reference Frames

### ISSUE THREAD

**Issue by optiluca** [UZ-SLAMLab/ORB_SLAM3#100]
Hi.  To identify the reference frame transformation between IMU and camera, the .yaml configuration files have the following:

```
# Transformation from camera to body-frame (imu)
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

```

Where in this example I'm using an identity matrix.  What I'm unclear on is what the camera reference frame is?  I.e., say I have an IMU with x forwards, y left, z up - what transformation do I need to put here? (or the rotation part of it anyway!)

Thanks,

Luca

**Comment by jdtardos** [comment]
Version 1.0 now includes documentation of the reference systems used, in file Calibration_Tutorial.pdf
