### ISSUE TITLE
Calibration file for the stereo case is not clear to me

### ISSUE THREAD

**Issue by cgringmuth** [UZ-SLAMLab/ORB_SLAM3#114]
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/Examples/Stereo/EuRoC.yaml#L37

I don't understand the parameters in the stereo case. It would be nice if you could elaborate on this a little. For example why are the parameters `Camera.fx`, `Camera.fy` etc. the same as in `LEFT.P`. However `LEFT.K` is not reflected in `LEFT.P`.
Isn't P = K[R|t], so for the left camera it should be basically the calibration matrix? Thus, `LEFT.P = LEFT.K[I|0]`. This is obviously not the case but for the general camera it is the case. 

And this is only necessary if the images not already rectified isn't it?

I would be very glad if you could explain a little or refer me to papers/books/articles etc. which explains this.

**Comment by jdtardos** [comment]
Check calibration_tutorial.pdf in version v1.0
