### ISSUE TITLE
Could you make support for equirectangular cameras?

### ISSUE THREAD

**Issue by amburkoff** [UZ-SLAMLab/ORB_SLAM3#115]
Thanks for the great scientific article and repository.
I am doing some scientific research using equirectangular cameras in slam algorithms.
Could you please do support for equirectangular cameras like in openvslam?

**Comment by jdtardos** [comment]
Sorry, we don't plan to support equirectangular cameras in near future.

**Comment by sadsasuke** [comment]
Is there any support for 360 cameras coming?
