### ISSUE TITLE
Question about relocalization in tracking.cc

### ISSUE THREAD

**Issue by xieqi1** [UZ-SLAMLab/ORB_SLAM3#120]
Hi !
  I notice the loop in line 3240, nCandidates is always 0, and the loop will not run. And I find in ORBSLAM2, nCandidates++ when detect a candidate frame via BOW.It seems it will always fail in relocalization, so is it a bug or you just drop the relocalization method?
Thank you !

**Comment by ankuPRK** [comment]
I think they have replaced relocalization with submap merging i.e. every new sequence will start with a new sub-map, which will then be aligned and merged with the one of the submaps in the set of maps we already have, given it meets certain criteria.

**Comment by xieqi1** [comment]
@ankuPRK Sure, I agree with your opinion.Thank you for your reply~

**Comment by ankuPRK** [comment]
welcome :)
