### ISSUE TITLE
Data for dense reconstruction

### ISSUE THREAD

**Issue by TTrambi** [UZ-SLAMLab/ORB_SLAM3#129]
Hi guys,

I want to use the output for dense reconstruction using a multi-view stereo tool like Colmap. Therefore, I do not only need the camera positions, but also the locations of the features in an image (2D) and the 3D feature points. (see https://colmap.github.io/format.html#sparse-reconstruction)

Getting the camera positions is straight forward, but how do I get the rest of the data I need?

**Comment by jdtardos** [comment]
These informations are stored in the map, but ORB-SLAM3 does not provide functions to export them. You will need to implement your own functions.
