### ISSUE TITLE
optimizer.cc中找到个比较严重的bug

### ISSUE THREAD

**Issue by tiantiandabaojian** [UZ-SLAMLab/ORB_SLAM3#133]
4055 行 obs2 << x, y;
x,y不是归一化相平面坐标吗，怎么能跟重投影做差呢
应该改成
float u = pKF2->fx * x + pKF2->cx;
float v = pKF2->fy * y + pKF2->cy;
obs2 << u, v;

**Comment by You-zeyi** [comment]
Do you mind rewriting your issue in English so that it could be understood by more people?

**Comment by greatoyster** [comment]
Translation version is below
in optimizer.cc, a bug was found in line 4055.
where obs2 << x, y; should be change to:
float u = pKF2->fx * x + pKF2->cx;
float v = pKF2->fy * y + pKF2->cy;
obs2 << u, v;
since x,y are normalize coodinates.

**Comment by colorDogs** [comment]
@tiantiandabaojian 加个联系方式呗?

**Comment by tiantiandabaojian** [comment]
> @tiantiandabaojian 加个联系方式呗?

qq  741299292  ~
