### ISSUE TITLE
make failed(undefined reference to symbol '_ZN2cv6String10deallocateEv') , can someone help me to solve this problem? 

### ISSUE THREAD

**Issue by wycjl** [UZ-SLAMLab/ORB_SLAM3#14]
:-1: error: CMakeFiles/stereo euroc.dir/Examples/Stereo/stereo euroc.cc.o: undefined reference to symbol '_ZN2cv6String10deallocateEv'

**Comment by ericzzj1989** [comment]
It is the same problem with ros in ORB-SLAM2
Add "-lboost_system" in Cmakelists.txt of ros example, like:

set(LIBS 
${OpenCV_LIBS} 
${EIGEN3_LIBS}
${Pangolin_LIBRARIES}
${PROJECT_SOURCE_DIR}/../../../Thirdparty/DBoW2/lib/libDBoW2.so
${PROJECT_SOURCE_DIR}/../../../Thirdparty/g2o/lib/libg2o.so
${PROJECT_SOURCE_DIR}/../../../lib/libORB_SLAM3.so
-lboost_system
)

**Comment by DreamWaterFound** [comment]
Besides "boost" problem, you may have a problem with multiple versions of OpenCV. Pay attention to cmake warnings, check cmake variables and link path after executed `cmake ..`. Custom installed OpenCV, ROS, and Anaconda may lead to this error. Without more information about your OS version, GCC/G++ version, OpenCV version and installed path, etc, I am sorry that I have no more detailed suggestions to help you.

Notice: this error is ENTIRELY about your own dependencies, not the author's problem. Give dislike will not help you solve any problems.

**Comment by jjgr3496** [comment]
As @DreamWaterFound, you may have duplicated libraries or multiple versions of OpenCV that maybe are messing with the linking step.Please, check wheter CMake is picking the correct path to OpenCV or if the version installed is above the minimum required. I suggest you to set the CMake verbose flag in order to track better the error.

**Comment by jjgr3496** [comment]
This bug was solved in #44.
