### ISSUE TITLE
Does ORB_SLAM3 update the camera extrinsic calibration?

### ISSUE THREAD

**Issue by ihamieh** [UZ-SLAMLab/ORB_SLAM3#140]
I'm not sure if ORB_SLAM3 outputs or updates the camera extrinsic calibration? I was able to output the camera and IMU trajectories but not sure about camera extrinsics? can someone please let me know?

**Comment by jdtardos** [comment]
No, you need to provide the camera extrinsic calibration, and ORB-SLAM3 does not modify it.

**Comment by ihamieh** [comment]
@jdtardos Do you estimate it somehow? Is camea extrinsic a constant input?

**Comment by jdtardos** [comment]
Extrinsic calibration is the relative poses between cameras in a stereo system, or the relative pose between the camera(s)  and the IMU sensor. A stereo system can be calibrated with the calibration tools in OpenCV. A visual-inertial system can be calibrated with kalibr.

**Comment by Chandanpanda** [comment]
where do you provide the extrinsic parameters?
