### ISSUE TITLE
Relocalization not working because of a missing line

### ISSUE THREAD

**Issue by schizzz8** [UZ-SLAMLab/ORB_SLAM3#143]
When testing Relocalization() I was not able to have it working properly.
I gave a look at the code in ORB_SLAM2 and I see that is missing a line.
Adding [here](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Tracking.cc#L3231):

```
                nCandidates++;
```
worked for me.

**Comment by richard-elvira** [comment]
Hello,

Yes, it is a bug that will be fixed in the next version.
