### ISSUE TITLE
The EuRoc dataset IMU coordinate system

### ISSUE THREAD

**Issue by 478161648** [UZ-SLAMLab/ORB_SLAM3#144]
hi,I want to know the orientation of the IMU coordinate system in EuRoc dataset. 
Is it a right-handed coordinate system? The y-axis points above the camera, and the z-axis points to the front of the camera?
thank you.

**Comment by jdtardos** [comment]
Version 1.0 now includes documentation of the reference systems in file Calibration_Tutorial.pfd
