### ISSUE TITLE
 How to decide the Tbc for Mono-inertial

### ISSUE THREAD

**Issue by ns15417** [UZ-SLAMLab/ORB_SLAM3#147]
Hi, Thanks for your work  and time.
I got a dataset on my own camera and IMU but not sure how to decide Tbc in the .yaml  file; here is the real relation between my IMU and camera : https://github.com/ns15417/ORB_SLAM3/blob/master/Result/IMU_CAMERA_POSE.jpg
based on this relation and my experience the Tbc here should be: 
 [0., 0., 1., 0.11602836,
 -1., 0., 0., 0.,
 0.,-1., 0., 0.23549999,
 0., 0., 0., 1.]
But i got a result looks like this: [https://github.com/ns15417/ORB_SLAM3/blob/master/Result/ORB-SLAM3_ori_Tbc.mkv](url)
I think that is maybe because the wrong Tbc ( because the camera forward direction changed from along x axis to z axis), so I changed it to:
 [1., 0., 0., 0.,
  0., 1., 0., -0.23549999,
  0., 0., 1., 0.11602836,
  0., 0., 0., 1.]
and then i got a better result like : [https://github.com/ns15417/ORB_SLAM3/blob/master/Result/ORB-SLAM3-2020-10-10_14.36.44.mkv](url)
 in which the size is still a problem and now i am not sure is it because the wrong Tbc or because the not-very-stable IMU data?

**Comment by ccamposm** [comment]
According to your sketch, your Tbc matrix should be like the first one. However I strongly recommend you to use some calibration library like kalibr (https://github.com/ethz-asl/kalibr) which will provide a full and more accurate calibration without any prior knowledge.
