### ISSUE TITLE
Problem:     Failed to load image at:......

### ISSUE THREAD

**Issue by fenjing** [UZ-SLAMLab/ORB_SLAM3#149]
Using the euroc dataset,after the camera parameters and orb extractor, can't load image. Should I add some other dll?

**Comment by liu-xiao-ke** [comment]
Have you solved it yet? I got the same problem. thx

**Comment by fenjing** [comment]
I have solved it by change its image path,looks like its length of path strings is stable.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UZ-SLAMLab/ORB_SLAM3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月20日(星期六) 下午3:27
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [UZ-SLAMLab/ORB_SLAM3] Problem:     Failed to load image at:...... (#149)





 
Have you solved it yet? I got the same problem. thx
