### ISSUE TITLE
Acceleration integration is not clear to me

### ISSUE THREAD

**Issue by cgringmuth** [UZ-SLAMLab/ORB_SLAM3#152]
Following lines are not clear to me:
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/src/ImuTypes.cc#L274-L275

Why is the acceleration multiplied by `0.5` when it is double integrated? However on the next line it is not. The factor is not correct in my opinion. 

So assuming you have an acceleration of 2 m/s^2 and integrate 2 times over 1 sec. It should return the travelled way after 1 s which should be 2m right? However it is 1m.

**Comment by jdtardos** [comment]
Basic high-school physics, In an uniformly accelerated motion:
V = V_0 + a * t
S = S_0 + V_0 * t + 1/2 * a * t^2
