### ISSUE TITLE
How to understand the update method of the covariance matrix in imutypes.cc?

### ISSUE THREAD

**Issue by AcresJoe1** [UZ-SLAMLab/ORB_SLAM3#160]
// Update covariance
C.rowRange(0,9).colRange(0,9) = A*C.rowRange(0,9).colRange(0,9)*A.t() + B*Nga*B.t();  
C.rowRange(9,15).colRange(9,15) = C.rowRange(9,15).colRange(9,15) + NgaWalk;

**Comment by tiantiandabaojian** [comment]
这就说来话长了，首先你需要去看On-Manifold Preintegration for Real-Time vio 这个论文
然后，这段代码对应了公式62，AB矩阵是他推导出来的噪声随着时间推移的状态延续矩阵
从i时刻到j时刻噪声的累计，ηij = A*ηij-1 + B*[ηgj-1, ηaj-1] 因为每次计算不能都从i时刻开始，这样太费时间
所以作者推导出了从上一时刻到当前时刻的变换过程，详细推一边论文你就懂啦

**Comment by AcresJoe1** [comment]
好的，非常感谢您！  @tiantiandabaojian
