### ISSUE TITLE
in ros save map?

### ISSUE THREAD

**Issue by chluck2008** [UZ-SLAMLab/ORB_SLAM3#17]
What can I do to save and load maps under ROS, and realize odometer under ROS

**Comment by w5543081** [comment]
same question，How can ORB-SLAM3  save maps ?  the interface of ORB-SLAM2  which is for saving map  is abandoned.

**Comment by chluck2008** [comment]
![2020-07-29 11-02-41屏幕截图](https://user-images.githubusercontent.com/35333200/88756445-3e600080-d196-11ea-80df-4379fb2446f3.png)

**Comment by varunns** [comment]
There is a piece of commented code, 2 methods : SaveAtlas and LoadAtlas in System.cc, looks like it is the relevant code, I am trying to find out the right place to make the calls to save the map

**Comment by richard-elvira** [comment]
The feature to save maps and load in a new session is currently in developing, We are going to publish it in the 0.4 version before of the end of the year.

**Comment by kwads123** [comment]
> The feature to save maps and load in a new session is currently in developing, We are going to publish it in the 0.4 version before of the end of the year.

@richard-elvira Do you have any update on when the save/load feature will be added?

**Comment by rebellojason7** [comment]
@richard-elvira is there any update with regard to this feature ? Thanks

**Comment by pavelsamoylenko** [comment]
@richard-elvira is there any update regard to map saving?

**Comment by cntzj** [comment]
@richard-elvira is there any update with regard to this feature ? Thanks

**Comment by richard-elvira** [comment]
Hi, sorry for the delay, we had been busy lately.

We are close to submitting a new version of the code with this functionality and a more optimized code to run faster.

**Comment by neo-knight-td** [comment]
When would you be able to provide this code ? @richard-elvira

**Comment by neo-knight-td** [comment]
Hi all,

Just made the Save/Load Atlas Functionality here https://github.com/UZ-SLAMLab/ORB_SLAM3/pull/310

Hope it helps !

**Comment by phdsky** [comment]
Any official update? Looking forward to v4.0...

**Comment by jdtardos** [comment]
Version 1.0 now includes map load and saving operations
