### ISSUE TITLE
No map

### ISSUE THREAD

**Issue by Ishira1601** [UZ-SLAMLab/ORB_SLAM3#177]
I'm trying to run the algorithm on data from a t265 realsense camera in an outdoor setting. I ran the following
`rosrun ORB_SLAM3 Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/Avant.yaml false`
Following is the "Avant.yaml file" :
```%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "KannalaBrandt8"

# Left Camera calibration and distortion parameters
Camera.fx: 286.94989013671875
Camera.fy: 286.8811950683594
Camera.cx: 419.09051513671875
Camera.cy: 396.1618957519531

# Kannala-Brandt distortion parameters
Camera.k1: -0.010033460333943367
Camera.k2: 0.04655449837446213
Camera.k3: -0.043029919266700745
Camera.k4: 0.007891562767326832

# Right Camera calibration and distortion parameters
Camera2.fx: 286.7814025878906
Camera2.fy: 286.8330078125
Camera2.cx: 415.67120361328125
Camera2.cy: 398.5335083

# Kannala-Brandt distortion parameters
Camera2.k1: -0.009146743454039097
Camera2.k2: 0.04491749033331871
Camera2.k3: -0.0417170487344265
Camera2.k4: 0.007513923

# Transformation matrix from right camera to left camera
Tlr: !!opencv-matrix
   rows: 3
   cols: 4
   dt: f
   data: [ 1.,   -0.001,   -0.05,   -0.064,
           0.001,   1.,   0.002,   0,
           0.005,    -0.002,   1.,   1.]

# Lapping area between images
Camera.lappingBegin: 0
Camera.lappingEnd: 511

Camera2.lappingBegin: 0
Camera2.lappingEnd: 511

# Camera resolution
Camera.width: 800
Camera.height: 848

# Camera frames per second 
Camera.fps: 20.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0
Camera.bf: 19.3079


# Transformation from body-frame (imu) to left camera
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-1., 0.0016, -0.006,0.011,
          -0.0016, -1., -0.002, 0.,
          -0.006, -0.002, 1., 0.,
          0.0, 0.0, 0.0, 1.0]

# IMU noise (Use those from /t265_front/gyro/imu_info)
IMU.NoiseGyro: 0.00000514 # 0.004 (VINS) # 0.00016 (TUM) # 0.00016    # rad/s^0.5
IMU.NoiseAcc: 0.00006695 # 0.04 (VINS) # 0.0028 (TUM) # 0.0028     # m/s^1.5
IMU.GyroWalk: 0.0000005 # 0.000022 (VINS and TUM) rad/s^1.5
IMU.AccWalk: 0.0001 # 0.0004 (VINS) # 0.00086 # 0.00086    # m/s^2.5
IMU.Frequency: 200
thFarPoints: 20.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # Tested with 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20 # 20
ORBextractor.minThFAST: 7 # 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500
```

![image](https://user-images.githubusercontent.com/45150814/98542057-025e3080-2299-11eb-9aeb-dacdb2ad875b.png)
I see the current frame, but I can't see the map on the map viewer. 

I don't get any any errors I can't see the map formation and I get the following warning

`Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.`

**Comment by macTracyHuang** [comment]
> I'm trying to run the algorithm on data from a t265 realsense camera in an outdoor setting. I ran the following `rosrun ORB_SLAM3 Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/Avant.yaml false` Following is the "Avant.yaml file" :
> 
> ```
> 
> #--------------------------------------------------------------------------------------------
> # Camera Parameters. Adjust them!
> #--------------------------------------------------------------------------------------------
> Camera.type: "KannalaBrandt8"
> 
> # Left Camera calibration and distortion parameters
> Camera.fx: 286.94989013671875
> Camera.fy: 286.8811950683594
> Camera.cx: 419.09051513671875
> Camera.cy: 396.1618957519531
> 
> # Kannala-Brandt distortion parameters
> Camera.k1: -0.010033460333943367
> Camera.k2: 0.04655449837446213
> Camera.k3: -0.043029919266700745
> Camera.k4: 0.007891562767326832
> 
> # Right Camera calibration and distortion parameters
> Camera2.fx: 286.7814025878906
> Camera2.fy: 286.8330078125
> Camera2.cx: 415.67120361328125
> Camera2.cy: 398.5335083
> 
> # Kannala-Brandt distortion parameters
> Camera2.k1: -0.009146743454039097
> Camera2.k2: 0.04491749033331871
> Camera2.k3: -0.0417170487344265
> Camera2.k4: 0.007513923
> 
> # Transformation matrix from right camera to left camera
> Tlr: !!opencv-matrix
>    rows: 3
>    cols: 4
>    dt: f
>    data: [ 1.,   -0.001,   -0.05,   -0.064,
>            0.001,   1.,   0.002,   0,
>            0.005,    -0.002,   1.,   1.]
> 
> # Lapping area between images
> Camera.lappingBegin: 0
> Camera.lappingEnd: 511
> 
> Camera2.lappingBegin: 0
> Camera2.lappingEnd: 511
> 
> # Camera resolution
> Camera.width: 800
> Camera.height: 848
> 
> # Camera frames per second 
> Camera.fps: 20.0
> 
> # Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
> Camera.RGB: 1
> 
> # Close/Far threshold. Baseline times.
> ThDepth: 40.0
> Camera.bf: 19.3079
> 
> 
> # Transformation from body-frame (imu) to left camera
> Tbc: !!opencv-matrix
>    rows: 4
>    cols: 4
>    dt: f
>    data: [-1., 0.0016, -0.006,0.011,
>           -0.0016, -1., -0.002, 0.,
>           -0.006, -0.002, 1., 0.,
>           0.0, 0.0, 0.0, 1.0]
> 
> # IMU noise (Use those from /t265_front/gyro/imu_info)
> IMU.NoiseGyro: 0.00000514 # 0.004 (VINS) # 0.00016 (TUM) # 0.00016    # rad/s^0.5
> IMU.NoiseAcc: 0.00006695 # 0.04 (VINS) # 0.0028 (TUM) # 0.0028     # m/s^1.5
> IMU.GyroWalk: 0.0000005 # 0.000022 (VINS and TUM) rad/s^1.5
> IMU.AccWalk: 0.0001 # 0.0004 (VINS) # 0.00086 # 0.00086    # m/s^2.5
> IMU.Frequency: 200
> thFarPoints: 20.0
> 
> #--------------------------------------------------------------------------------------------
> # ORB Parameters
> #--------------------------------------------------------------------------------------------
> 
> # ORB Extractor: Number of features per image
> ORBextractor.nFeatures: 1000 # Tested with 1250
> 
> # ORB Extractor: Scale factor between levels in the scale pyramid
> ORBextractor.scaleFactor: 1.2
> 
> # ORB Extractor: Number of levels in the scale pyramid
> ORBextractor.nLevels: 8
> 
> # ORB Extractor: Fast threshold
> # Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
> # Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
> # You can lower these values if your images have low contrast
> ORBextractor.iniThFAST: 20 # 20
> ORBextractor.minThFAST: 7 # 7
> 
> #--------------------------------------------------------------------------------------------
> # Viewer Parameters
> #--------------------------------------------------------------------------------------------
> Viewer.KeyFrameSize: 0.05
> Viewer.KeyFrameLineWidth: 1
> Viewer.GraphLineWidth: 0.9
> Viewer.PointSize: 2
> Viewer.CameraSize: 0.08
> Viewer.CameraLineWidth: 3
> Viewer.ViewpointX: 0
> Viewer.ViewpointY: -0.7
> Viewer.ViewpointZ: -3.5
> Viewer.ViewpointF: 500
> ```
> 
> ![image](https://user-images.githubusercontent.com/45150814/98542057-025e3080-2299-11eb-9aeb-dacdb2ad875b.png) I see the current frame, but I can't see the map on the map viewer.
> 
> I don't get any any errors I can't see the map formation and I get the following warning
> 
> `Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.`


may i know how you solved this issue, plz
