### ISSUE TITLE
ROS-Node export definitiv image poses

### ISSUE THREAD

**Issue by jonasmeyer1** [UZ-SLAMLab/ORB_SLAM3#204]
Hi, thanks for the great work.
I am using the ROS Stereo-Inertial Node to process recorded data (ROS-Bag). How can I export the final image poses at the end of the SLAM processing? Does anyone have a simple solution?

**Comment by janis8008** [comment]
Add
  ```
SLAM.Shutdown();

    // Save camera trajectory
  SLAM.SaveKeyFrameTrajectoryTUM("Results/results_key_frame.txt");
  SLAM.SaveTrajectoryEuRoC("Results/results_tra.txt");
  ros::shutdown();
```
To ROS example source code, rebuild examples, and after your .bag file ends do 
`rosnode kill -a` to stop all nodes and start saving trajectory data

**Comment by jonasmeyer1** [comment]
Thanks for your answer. I just found the same solution in the code for the stereo-Node.
