### ISSUE TITLE
The RGBD SLAM perform worse than ORB SLAM2

### ISSUE THREAD

**Issue by ZhouXiner** [UZ-SLAMLab/ORB_SLAM3#208]
I try to run the RGBD type in TUM RGBD Dataset, but the performance is even worse than ORBSLAM2 in some sequence like fr1_desk2. Has anyone struggled the same problem like me?

**Comment by janis8008** [comment]
How is it worse? 
Only changes in code compared to ORB-SLAM2 are :
`ORB_SLAM3`
`CV_LOAD_IMAGE`
And the difference in the Slam system is added imu support.
I don't think they changed the way how no Imu systems work.

**Comment by ZhouXiner** [comment]
> How is it worse?
> Only changes in code compared to ORB-SLAM2 are :
> `ORB_SLAM3`
> `CV_LOAD_IMAGE`
> And the difference in the Slam system is added imu support.
> I don't think they changed the way how no Imu systems work.

Thanks for reply.
The APE is bigger in TUM RGBD dataset like fr1_desk2 and fr1_room.
Actually, the loop closuing part also changed a lot.
Maybe I should compare the preformance without loop.

**Comment by melhashash** [comment]
I am experiencing the same issue with the monocular pipeline; the accuracy is worse than ORB-SLAM2.

**Comment by CSU-NXY** [comment]
I've tested ORB-SLAM2 and ORB-SLAM3 on KITTI dataset in RGBD mode with my deep learning model predicted depth. It turns out that ORB-SLAM3 performs worse than ORB-SLAM2 and have scale drift issues.

**Comment by CSU-NXY** [comment]
Hi, @ZhouXiner @melhashash Try this solution #107. It seems the RGBD mode didn't set mbf value correctly.

**Comment by ZhouXiner** [comment]
> Hi, @ZhouXiner @melhashash Try this solution #107. It seems the RGBD mode didn't set mbf value correctly.

Thanks, I will try it.

**Comment by melhashash** [comment]
> Hi, @ZhouXiner @melhashash Try this solution #107. It seems the RGBD mode didn't set mbf value correctly.

Thanks for your suggestion, but I am talking about the monocular case.

**Comment by thomCastillo** [comment]
Could we add depth sensor error as parameter(i.e noise parameter in IMU) to optimization in RGB-D SLAM? If so, how can we add it?

**Comment by UcefMountacer** [comment]
@ZhouXiner can you give me the link to dataset and the command? I tried on freiburg desk dataset but it doesn't work for me.

**Comment by jdtardos** [comment]
Version v1.0 has corrected some bugs in RGB-D SLAM
