### ISSUE TITLE
Inconsistent trajectory

### ISSUE THREAD

**Issue by chu-z** [UZ-SLAMLab/ORB_SLAM3#209]
Hello, I'm having issues with trajectory for Stereo_Inertial mode. I'm using a rosbag, recorded with intel T265 camera.
I discovered the trajectory as shown on ORB_SLAM3 isn't consistent throughout the 3 attempts on a same rosbag with the same configs. Inconsistencies are based in terms of the path deviation, and the trajectory exhibit a different route after sometime, as output by ORB_SLAM, is this common?

**Comment by janis8008** [comment]
There was a post about this some time ago. Hope it helps.

https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/68

**Comment by chu-z** [comment]
@janis8008 Thanks for the link, it was helpful :+1:
