### ISSUE TITLE
Why to use camera->world position when plotting and writing to file trajectory

### ISSUE THREAD

**Issue by dimaxano** [UZ-SLAMLab/ORB_SLAM3#224]
I found that everywhere where trajectory should be saved to file or plotted in pangolin ORB_SLAM3 uses camera->world position, not world->camera? Like [here](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/src/MapDrawer.cc#L175) and [here](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/src/System.cc#L564)

Does it really matter what type of position to use (wc or cw) and will anything really change if I replace camera->world with world->camera?

**Comment by jdtardos** [comment]
It does not matter the convention you use, provided that you use it correctly.
