### ISSUE TITLE
Using ORB-SLAM3 with stereo camera in gazebo

### ISSUE THREAD

**Issue by kazuma-takeuchi-jpn** [UZ-SLAMLab/ORB_SLAM3#225]
Hi!
I'm trying to run ORB-SLAM3 with stereo camera in gazebo. I use ros melodic to do these things. Stereo camera works well, and ros topic about left and right camera is in the rostopic list. However, when I try to run ORB-SLAM3, it subscribe only left camera topic, in other words, only the image on the left side of the camera will be displayed.

![Screenshot from 2020-12-23 17-13-16](https://user-images.githubusercontent.com/76512537/102977127-e90dfc80-4545-11eb-99ab-aec2e0218542.png)

This is the simulation environment.

![Screenshot from 2020-12-23 17-30-56](https://user-images.githubusercontent.com/76512537/102977141-ef03dd80-4545-11eb-91ee-e4c945c6a9f4.png)

This is the screen shot when I tried to run ORB-SLAM3

Does anyone know how to solve this problems? I thank you in advance, and Merry Christmas!

**Comment by prasanna229** [comment]
hey did you slove the isssue...cz can you help me with it?

**Comment by ababayi** [comment]
Hi, Can I access to your code?
