### ISSUE TITLE
Do any one solve the bug of SaveAtlas() and LoadAtlas()!!!

### ISSUE THREAD

**Issue by HappyXY** [UZ-SLAMLab/ORB_SLAM3#228]
i want to save the map and reuse the map for localization, there are some errors:
"Starting to write the save binary file
libc++abi.dylib: terminating with uncaught exception of type boost::archive::archive_exception: unregistered class - derived class not registered or exported "

if any one can save and load map successfully, please share the methods!
Thanks very much !!!

**Comment by cntzj** [comment]
Have you solved this problem?

**Comment by xinruozhishui201314** [comment]
我也在解决这个问题，要不大家加一下联系方式吧，可以更方便的沟通，我微信号：15517920165

**Comment by xinruozhishui201314** [comment]
我現在能正常保存，加載還有點問題，在解決。

**Comment by xinruozhishui201314** [comment]
@HappyXY 這個已經解決

**Comment by neo-knight-td** [comment]
Could you provide you modifications ? @xinruozhishui201314

**Comment by jdtardos** [comment]
Version v1.0 includes map loading and saving operations
