### ISSUE TITLE
Input camera pose from outside and update globally

### ISSUE THREAD

**Issue by wzhwzh94** [UZ-SLAMLab/ORB_SLAM3#230]
I want to replace every frame's camera pose with exact value from outside in real time, and update all relevant maps in atlas, what should I do? Is there any functions I can use or refer to? 
Thanks a lot.

**Comment by NJNischal** [comment]
Hello @wzhwzh94 were you able to figure out how to do this? If yes could you please share your approach for it? Thank you!
