### ISSUE TITLE
PoseOptimization deviation

### ISSUE THREAD

**Issue by wzhwzh94** [UZ-SLAMLab/ORB_SLAM3#249]
Test in Stereo Kitti without imu.
1. Replace the initial position estimated by mVelocity with the real value from kitti gt_poses for each frame.
2. SearchByProjection using the real value and get mvpMapPoints.
3. PoseOptimization using the mvpMapPoints and the real value, the estimate result always has a 1~30 cm deviation. The trajectory file's translational error goes down from 0.5% to 0.2%, using kitti-odom-eval-master.
4. If not PoseOptimization, I get a trajectory file with translational error 1e-5%.

What is PoseOptimization's margin of error? Is the 1~30 cm deviation normal? Or maybe there is an error in the standard trajectory?

**Comment by boomzoeycy** [comment]
Hi！I replaced the initial position estimated by mVelocity with other real value . After that ,when I started to run the node(stereo), terminal always showed "core dumped". The trajectory would began to shift suddenly at some point. I dont know why...
