### ISSUE TITLE
OpenCV4 support

### ISSUE THREAD

**Issue by henrychoi** [UZ-SLAMLab/ORB_SLAM3#257]
Ubuntu foxy is OpenCV3 by default.  Can you please share the roadmap?

**Comment by Germanunkol** [comment]
There's a pull request on ORB SLAM2 which upgraded it to OpenCV4, specifically this commit: https://github.com/Windfisch/ORB_SLAM2/commit/379c7633191b178b19a7c635b9df0fe370b05b6d

Applying almost the exact same changes to ORB SLAM3 worked well for me (Ubuntu 20.04).

**Comment by versatran01** [comment]
I have a working verions here https://github.com/versatran01/orb_slam3/tree/opencv4

**Comment by jdtardos** [comment]
Version v1.0 has been tested with OpenCV3 and OpenCV4
