### ISSUE TITLE
How to Close ORB-SLAM3?

### ISSUE THREAD

**Issue by Kanishk598** [UZ-SLAMLab/ORB_SLAM3#260]
I want to close ORB-SLAM3 by pressing CTRL+C, but it isn't closing. The Cross button on the Map Viewer window isn't working and the Current Frame window is getting reopened every time I'm closing it with the Cross button. And workaround?
Thanks

Update: It seems eventually killing the terminal with running process is the only way possible, but I'd like if someone gives any other clean method.

**Comment by wzhwzh94** [comment]
Try like this:
https://github.com/NERanger/ORB-SLAM2-with-D435i/blob/master/Examples/RGB-D/rgbd_realsense.cc

**Comment by Kanishk598** [comment]
> Try like this:
> https://github.com/NERanger/ORB-SLAM2-with-D435i/blob/master/Examples/RGB-D/rgbd_realsense.cc

Can you please tell me how am I supposed to use this code? 
I'm a beginner in ROS, any help is greatly appreciated 😃

**Comment by Kanishk598** [comment]
Thank you, there was some temporary bug which is solved now. Pressing CTRL+C on the terminal running ORB is closing ORB3 without any difficulty or error. 
I am closing this issue.
