### ISSUE TITLE
Save/Load Atlas V0.4

### ISSUE THREAD

**Issue by neo-knight-td** [UZ-SLAMLab/ORB_SLAM3#301]
Was the save/load atlas functionality implemented in version V0.4 ? It seems like a lot of code related to serialization and atlas save/load has been deleted in that version. Is it the point to release it later ?

**Comment by fliegend** [comment]
Same concern. Actually save/load atlas could work with minor modifications in serialize(Archive &ar, const unsigned int version). Hope it will be released later

**Comment by neo-knight-td** [comment]
@fliegend meanwhile I made a pull request with the Save/Load Functionnality. You can review it here https://github.com/UZ-SLAMLab/ORB_SLAM3/pull/310. Hope it helps

**Comment by fliegend** [comment]
> @fliegend meanwhile I made a pull request with the Save/Load Functionnality. You can review it here #310. Hope it helps

Many thanks:). Another problem from my side is that it saves too much data, which makes the stored .bin file too large. Any ideas to shrink saved map size?

**Comment by neo-knight-td** [comment]
@fliegend You're welcome ! 
On what device are you running ORB SLAM 3? Do you come to a shortage in memory on your device ? Or is it the serialization that gives you an error? 
Serialization is just transforming the classes in a bit stream. So if you perform compression on that stream you should be able to reduce the size of your file. This should be useful I think https://stackoverflow.com/a/48034742/15539525. It is part of boost so you should not have to perform that many changes to the code.

**Comment by fliegend** [comment]
> @fliegend You're welcome !
> On what device are you running ORB SLAM 3? Do you come to a shortage in memory on your device ? Or is it the serialization that gives you an error?
> Serialization is just transforming the classes in a bit stream. So if you perform compression on that stream you should be able to reduce the size of your file. This should be useful I think https://stackoverflow.com/a/48034742/15539525. It is part of boost so you should not have to perform that many changes to the code.

Probably this is a good solution, I'll have a try, thanks!

**Comment by treememory** [comment]
do not save image(mat), cloud shrink lot

**Comment by Jiaxin8122** [comment]
> > @fliegend You're welcome !
> > On what device are you running ORB SLAM 3? Do you come to a shortage in memory on your device ? Or is it the serialization that gives you an error?
> > Serialization is just transforming the classes in a bit stream. So if you perform compression on that stream you should be able to reduce the size of your file. This should be useful I think https://stackoverflow.com/a/48034742/15539525. It is part of boost so you should not have to perform that many changes to the code.
> 
> I run in ubuntu 16.04 with ros kinetic. Memory isn't a problem, just the saved map is larger compared to ORB-SLAM2.
> Probably this is a good solution, I'll have a try, thanks!

Hello, 

I can't find the V0.4 version but the newest version has no function like Save/Load . I use ubuntu 16.04 and ros as well. Could you share the V0.4 version? Maybe we can add wechat or with email.  austin.jxhuang@gmail.com

regards

**Comment by jdtardos** [comment]
Version v1.0 includes map loading and saving operations
