### ISSUE TITLE
Monocular (without inertial) examples fail with 0.4

### ISSUE THREAD

**Issue by Bloodwyn** [UZ-SLAMLab/ORB_SLAM3#302]
Hi, it seems like the Monocular-only examples don't work with the newest version. 
Everything seems to get loaded in properly, but the system won't track anything.
With any TUM dataset it will only play the video but does not show any keypoints nor the "trying to intialize" message.

As Monocular-intertial still works in 0.4 and Monocular-only used to work in previous version I expect a bug in the latest release.

Can someone confirm this? Thanks.

**Comment by Bloodwyn** [comment]
FIX: change line 106 in file mono_tum_vi.cc to use cv::IMREAD_GRAYSCALE

**Comment by sadsasuke** [comment]
Hi, I am facing the same issue. I changed the line 106 but still same problem. any help . @Bloodwyn ?

**Comment by sadsasuke** [comment]
> FIX: change line 106 in file mono_tum_vi.cc to use cv::IMREAD_GRAYSCALE

Can you please tell me the steps you did after you made the change in .cc file .. I am a bit new to coding. Thanks in advance
