### ISSUE TITLE
Sources of nondeterministic behavior

### ISSUE THREAD

**Issue by mihaibujanca** [UZ-SLAMLab/ORB_SLAM3#307]
I would like to try to characterize the degree of variability between runs and reduce it to whatever degree this is possible.
This would allow for improved reproducibility on benchmarks and possibly improving guidelines for choosing hyperparameters based on the specific use case.

Currently, I can think of the following sources:
- Multithreading
- Widespread use of RANSAC
- Keyframe selection
- Other elements in pose optimisation?

Even if getting to fully deterministic behavior might be too big of a task, some help in identifying the sources of randomness and some bounds would be greatly appreciated.

Relevant threads / resources:
https://github.com/raulmur/ORB_SLAM2/issues/45
https://github.com/raulmur/ORB_SLAM2/issues/283

**Comment by jdtardos** [comment]
You are correct, multithreading, RANSAC and Keyframe selection are the main sources of non-deterministic behavior. Fixing RANSAC is doable, but I don't think that fixing multithreading is doable, and it influences keyframe creation.
