### ISSUE TITLE
Excessive RAM usage when building 

### ISSUE THREAD

**Issue by MarcusDudeBro** [UZ-SLAMLab/ORB_SLAM3#329]
When I try building ORB SLAM 3 with the build.sh script, I see about 12 cc1plus processes emerge. As the build script continues to run, these processes progressively use more memory, eventually using 100% of my systems memory, and crashing my OS. This usually happens while a very large number of c++ compilation warnings are being outputted. I am running Ubuntu 20.04 on a virtual machine, with 13 GB of RAM. No error messages are being thrown, I have installed all the dependencies, and performed all the steps previous to the one saying to run the build.sh script.

**Comment by gotiobg** [comment]
https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/118#issuecomment-726648539
