### ISSUE TITLE
Question about Tracking::CreateNewMapPoints() function

### ISSUE THREAD

**Issue by Taeyoung96** [UZ-SLAMLab/ORB_SLAM3#363]
@richard-elvira   
Thanks for your great work! :smile:    
I have a question about the function in the `Tracking` class.  

In `Tracking` class, there is a function named `CreateNewMapPoints()`.  
The function is declared, but I can't find where to use it.  

I find that there is a function with the same name in the `LocalMapping` class.  
It uses in `void LocalMapping::Run()`.  

My question is, how are these two functions different?  
Is `void Tracking::CreateNewMapPoints()` useless?  

Thanks,

**Comment by wangtsiao** [comment]
Seems Tracking::CreateNewMapPoints() and LocalMapping::CreateNewMapPoints() are implemented for same goal. 

ORB_SLAM3 are developed based on ORB_SLAM2,  maybe Tracking::CreateNewMapPoints() are used in ORB_SLAM2, it's indeed useless in ORB_SLAM3.
