### ISSUE TITLE
Build fatal error: openssl/md5.h missing file

### ISSUE THREAD

**Issue by buemi** [UZ-SLAMLab/ORB_SLAM3#373]
Hi,
I'm building the source code in Ubuntu 18.04.
I receive this error during the build process (thirdparty building ends successfully):

_fatal error: openssl/md5.h: No such file or directory
 #include <openssl/md5.h>_

I tried to install libssl-dev through the apt-get command, but the output is:

 _"the packege is not a candidate for installation"_

Any suggestion is welcome

**Comment by buemi** [comment]
Solved by installing libssl-dev from source [(https://www.openssl.org/source/)]

**Comment by stellarpower** [comment]
This should probably be added to the CMake recipe.

**Comment by btilmon** [comment]
`sudo apt-get install libssl-dev` works for me on Ubuntu 18.04.6 LTS
