### ISSUE TITLE
Did stereo-inertial provide an online calibration for extrinsic parameters and time?

### ISSUE THREAD

**Issue by qiaozhijian** [UZ-SLAMLab/ORB_SLAM3#39]

**Comment by xiefei2929** [comment]
Seems not. 
It relies heavily on calibration accuracy.

**Comment by jdtardos** [comment]
No, you should perform off-line calibration, for example using https://github.com/ethz-asl/kalibr

**Comment by qiaozhijian** [comment]
I tested it on my robot and I made sure that my timestamp and external calibration are accurate (calibrated by kalibr), but the system crashes because of a bad BA everytime

**Comment by jdtardos** [comment]
Could you please provide more information about the crash?

**Comment by qiaozhijian** [comment]
yes! I'm willing! it is as follows:

`last KF is empty!
9.4599269222115634
not enough acceleration
last KF is empty!
First KF:0; Map init KF:0
New Map created with 477 points
IMU in Map 0 is initialized
start VIBA 1
end VIBA 1
Not enough motion for initializing. Reseting...
TRACK: Reset map because local mapper set the bad imu flag 
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 159
mnInitialFrameId = 0
164 Frames had been set to lost
last KF is empty!
not IMU meas
last KF is empty!
9.3207136995208799
not enough acceleration
last KF is empty!
First KF:26; Map init KF:0
New Map created with 203 points`

Vins-fusion and open-vins can achieve good results on the same data set. If needed, I can provide my dataset and parameter file.

**Comment by qiaozhijian** [comment]
- last KF is empty!
9.4698022330497551
not enough acceleration
last KF is empty!
9.4720551031521705
not enough acceleration
last KF is empty!
9.4578314637517362
not enough acceleration
last KF is empty!
9.4599269222115634
not enough acceleration
last KF is empty!
First KF:0; Map init KF:0
New Map created with 477 points
IMU in Map 0 is initialized
start VIBA 1
end VIBA 1
Not enough motion for initializing. Reseting...
TRACK: Reset map because local mapper set the bad imu flag 
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 159
mnInitialFrameId = 0
164 Frames had been set to lost
last KF is empty!
not IMU meas
last KF is empty!
9.3207136995208799
not enough acceleration
last KF is empty!
First KF:26; Map init KF:0
New Map created with 203 points

**Comment by xiefei2929** [comment]
VINS has great online calibration capability, you cannot make sure your  parameters are  accurate.

**Comment by qiaozhijian** [comment]
> VINS has great online calibration capability, you cannot make sure your parameters are accurate.

maybe. But I see the result of VINS online calibration is not  accurate, so I don't use online calibration when I use VINS. but I use in open-vins

**Comment by ccamposm** [comment]
It seems there is not enough motion for accurately initializing inertial parameters (Maybe camera remains steady for some time just after initializing?). However, since you are using a stereo-inertial setup, you could try commenting from line 138 to 145 at LocalMapping.cc:
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/LocalMapping.cc#L138
This check is specially important for monocular-inertial case, where scale also needs to be estimated, but not for stereo-inertial one.

**Comment by qiaozhijian** [comment]
Thank you for your suggestion. I modified it according to your suggestion. My system did run for a while longer than before (although the effect was not as good as STEREO), but after a while the robot began to "fall into the ground", although my robot only moved on the ground.

**Comment by qiaozhijian** [comment]
> It seems there is not enough motion for accurately initializing inertial parameters (Maybe camera remains steady for some time just after initializing?). However, since you are using a stereo-inertial setup, you could try commenting from line 138 to 145 at LocalMapping.cc:
> https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/LocalMapping.cc#L138
> This check is specially important for monocular-inertial case, where scale also needs to be estimated, but not for stereo-inertial one.

Thank you for your suggestion. I modified it according to your suggestion. My system did run for a while longer than before (although the effect was not as good as STEREO), but after a while the robot began to "fall into the ground", although my robot only moved on the ground.

**Comment by qiaozhijian** [comment]
> It seems there is not enough motion for accurately initializing inertial parameters (Maybe camera remains steady for some time just after initializing?). However, since you are using a stereo-inertial setup, you could try commenting from line 138 to 145 at LocalMapping.cc:
> https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/LocalMapping.cc#L138
> This check is specially important for monocular-inertial case, where scale also needs to be estimated, but not for stereo-inertial one.

My robot does walk for a while and stops for a while, and it only has two modes of motion: straight and rotating respectively.

**Comment by ccamposm** [comment]
Thank you for the update.
Inertial parameters estimation requires enough accelerometer and gyroscope excitation, which is achieved by performing aggressive motion. In addition, having gravity vector always pointing at the same direction (i.e ground robot) usually leads to bad results. Is that your case?
You could also check values for estimated biases, they should be close to zero.

**Comment by qiaozhijian** [comment]
Yes, it's my case. And you are right: bias of ACC_Z is too big

**Comment by qiaozhijian** [comment]
> Thank you for the update.
> Inertial parameters estimation requires enough accelerometer and gyroscope excitation, which is achieved by performing aggressive motion. In addition, having gravity vector always pointing at the same direction (i.e ground robot) usually leads to bad results. Is that your case?
> You could also check values for estimated biases, they should be close to zero.

Yes, it's my case. And you are right: bias of ACC_Z is too big

**Comment by ccamposm** [comment]
You could try increasing prior information for accelerometer bias to force it to remain close to zero (increase input argument priorA at https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/LocalMapping.cc#L167)
or even fixing acc bias to zero during initialization since it is quite likely to converge to the right value during posterior Local BAs.
