### ISSUE TITLE
libpango_windowing.so

### ISSUE THREAD

**Issue by NhlalalaDylan** [UZ-SLAMLab/ORB_SLAM3#399]
when I run :  ./Examples/Monocular/mono_euroc ./Vocabulary/ORBvoc.txt ./Examples/Monocular/EuRoC.yaml ~/Datasets/EuRoc/MH01 ./Examples/Monocular/EuRoC_TimeStamps/MH01.txt dataset-MH01_mono

I get:
./Examples/Monocular/mono_euroc: error while loading shared libraries: libpango_windowing.so: cannot open shared object file: No such file or directory

**Comment by maghauke** [comment]
sudo ldconfig

**Comment by NhlalalaDylan** [comment]
Thanks a lot

**Comment by Mechazo11** [comment]
@maghauke Thank you very much for providing the solution. I am a novice when it comes to using C++ projects and was wondering what is ldconfig doing in context of ORB-SLAM3?

**Comment by AllenIsaacJose** [comment]
> @maghauke Thank you very much for providing the solution. I am a novice when it comes to using C++ projects and was wondering what is ldconfig doing in context of ORB-SLAM3?

After installing Pangolin libraries, it's a good idea to update the library cache using this command. Pangolin is the visualizing library used in ORB-SLAM 1, 2, and 3.

**Comment by jiyooonp** [comment]
Hello, I tried to run the command, but it is still giving me the error. Could someone help me? Thank you.

**Comment by GLtangzero** [comment]
@jiyooonp 
Hey, first you need check which *.so document you can't find.
Then try to find the path of it.
For example I got the error like:
`error while loading shared libraries: libORB_SLAM3.so: cannot open shared object file: No such file or directory`
Then I found this .os document in /home/user/ORBSLAM3_ROS2_2/src/ORB_SLAM3/lib,
next input `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/ORBSLAM3_ROS2_2/src/ORB_SLAM3/lib`
in your terminal or just write it in the `.bashrc` and `source ~/.bashrc`.
It maybe will work, please check it.

**Comment by Strikerfury22** [comment]
@jiyooonp 
Hello, I was having the same problem. Once you have made what @GLtangzero said to declare your $LD_LIBRARY_PATH, execute "sudo ldconfig $LD_LIBRARY_PATH". In that way ldconfig will create the necessary links. In my case, my $LD_LIBRARY_PATH only contained the directory, so no ":" were in it. This is what it contained: "/path/to/my/lib". I hope this helps everyone in our same situation (I just managed to make it right now).

**Comment by Adithya1911** [comment]
Hello, I was facing the problem, 
./test_webcam_2: error while loading shared libraries: libOpenNI2.so.0: cannot open shared object file: No such file or directory
Launching ORB_SLAM3 with Monocular sensor
when i try to run the ORBSLAM3 this is first time i am facing this issue
