### ISSUE TITLE
Map save/load

### ISSUE THREAD

**Issue by 1hada** [UZ-SLAMLab/ORB_SLAM3#408]
Are there any plans for [SaveMap()](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/578500b836ea05be40d6188b815bb0ddbcdc75f1/include/System.h#L160) ?

Can I help on that somehow?

**Comment by Sherlock-hh** [comment]
you can check the pull requests, search "save", you can found someone already did that.

**Comment by 1hada** [comment]
Thank you!
