### ISSUE TITLE
how to define  World coordinate system 

### ISSUE THREAD

**Issue by Sherlock-hh** [UZ-SLAMLab/ORB_SLAM3#409]
hello, thanks for your brilliant work! I have some questionI’m tring to transform the camera pose(x,y,z, q()) to World coordinate system. then I refer to the function" SaveTrajectoryEuRoC"
I found the if slam system used imu means use the imu coordinate system **Twb** (imu position is (0,0,0)), else used the keyFrames ’s coor**Twc**, but I don't understand, how to define the world coordinate system? Is it the first frame as the original center? and used the **Twc** means to transform the world to current fram coordinate, so the code 
```

  cv::Mat Trw = cv::Mat::eye(4, 4, CV_32F);

        // If the reference keyframe was culled, traverse the spanning tree to get a suitable keyframe.
        if (!pKF)
            continue;
        while (pKF->isBad())
        {
            Trw = Trw * pKF->mTcp;
            pKF = pKF->GetParent();
        }

        if(!pKF || pKF->GetMap() != pBiggerMap)
        {
            continue;
        }
        Trw = Trw * pKF->GetPose() * Twb; // Tcp*Tpw*Twb0=Tcb0 where b0 is the new world reference

```
Trw means reference to world；
pKF->GetPose() = Twc means world to current;
Twb means world to imu；
I don't understand why it‘s finally qual to Trw？

and  then：

```
        if (mSensor == IMU_MONOCULAR || mSensor == IMU_STEREO)
        {
            cv::Mat Tbw = pKF->mImuCalib.Tbc*(*lit)*Trw;
            cv::Mat Rwb = Tbw.rowRange(0,3).colRange(0,3).t();
            cv::Mat twb = -Rwb*Tbw.rowRange(0,3).col(3);
            vector<float> q = Converter::toQuaternion(Rwb);
            f << setprecision(6) << 1e9*(*lT) << " " <<  setprecision(9) << twb.at<float>(0) << " " << twb.at<float>(1) << " " << twb.at<float>(2) << " " << q[0] << " " << q[1] << " " << q[2] << " " << q[3] << endl;
        }
        else
        {
            cv::Mat Tcw = (*lit)*Trw;
            cv::Mat Rwc = Tcw.rowRange(0,3).colRange(0,3).t();
            cv::Mat twc = -Rwc*Tcw.rowRange(0,3).col(3);
            vector<float> q = Converter::toQuaternion(Rwc);
            f << setprecision(6) << 1e9*(*lT) << " " <<  setprecision(9) << twc.at<float>(0) << " " << twc.at<float>(1) << " " << twc.at<float>(2) << " " << q[0] << " " << q[1] << " " << q[2] << " " << q[3] << endl;
        }

```
what means Tbw? imu to world coordinate system? why transform like that?
I'll be very thankful that if there's some one can help me to figure out the coordinate transform, thank you very much!

**Comment by jdtardos** [comment]
For pure visual SLAM, the World reference used is the first camera pose. For visual-inertial, once IMU is initialized, the world reference is rotated to have vertical z axis.
