### ISSUE TITLE
How to deal with IMU-camera time difference

### ISSUE THREAD

**Issue by yaelbenoren** [UZ-SLAMLab/ORB_SLAM3#411]
Hello,
When I run Kalibr for calibrating the camera with the IMU I see there is a slight difference between the IMU clock and the camera clock. How does ORB_SLAM deal with this? I did not see any mention of this in the yaml.

**Comment by jdtardos** [comment]
ORB-SLAM3 assumes that sensors are synchronized. You will need to manually correct the issue.
