### ISSUE TITLE
terminate called after throwing an instance of 'cv::Exception'

### ISSUE THREAD

**Issue by FeiXie8** [UZ-SLAMLab/ORB_SLAM3#421]
`
ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Stereo

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Creation of new map with id: 0
Creation of new map with last KF id: 0
Seq. Name: 

Camera Parameters: 
- Camera: Pinhole
- fx: 653.071
- fy: 653.071
- cx: 661.736
- cy: 366.981
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 20
- color order: BGR (ignored if grayscale)

Depth Threshold (Close/Far Points): 4.2

ORB Extractor Parameters: 
- Number of Features: 1200
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7
First KF:0; Map init KF:0
New Map created with 404 points
TRACK_REF_KF: Less than 15 matches!!
Fail to track local map!
Creation of new map with id: 1
Exits current map 
Saved map with ID: 0
Creation of new map with last KF id: 7
First KF:7; Map init KF:7
New Map created with 96 points
Fail to track local map!
Fail to track local map!
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 252
2 Frames set to lost
First KF:8; Map init KF:7
New Map created with 73 points
Fail to track local map!
Fail to track local map!
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 259
0 Frames set to lost
First KF:9; Map init KF:8
New Map created with 340 points
TRACK_REF_KF: Less than 15 matches!!
Fail to track local map!
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 463
0 Frames set to lost
First KF:11; Map init KF:9
New Map created with 185 points
Fail to track local map!
Fail to track local map!
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 489
0 Frames set to lost
First KF:15; Map init KF:11
New Map created with 50 points
TRACK_REF_KF: Less than 15 matches!!
Fail to track local map!
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 537
0 Frames set to lost
First KF:16; Map init KF:15
New Map created with 320 points
Fail to track local map!
Fail to track local map!
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 559
0 Frames set to lost
First KF:19; Map init KF:16
New Map created with 73 points
Fail to track local map!
Relocalized!!
TRACK_REF_KF: Less than 15 matches!!
Fail to track local map!
Creation of new map with id: 2
Exits current map 
Saved map with ID: 1
Creation of new map with last KF id: 27
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.2) /home/xiefei/package/opencv-4.5.2/modules/core/src/lapack.cpp:851: error: (-215:Assertion failed) type == CV_32F || type == CV_64F in function 'invert'
`

[1]    16951 abort (core dumped)  rosrun orbslam3 mynteye_orbslam   false
**I run the stereo slam on my own camera.It can work ,but when lose the localization and need to be relocalize,it will randomly happen.**

**Comment by chetanpandey1266** [comment]
![image](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/55939332/0e431f41-fe20-4010-aab4-24f3fb0606d2)
I tried running the example with pangolin but I am getting this. Howb you were able to solve it?
