### ISSUE TITLE
core dump when create a new map

### ISSUE THREAD

**Issue by FeiXie8** [UZ-SLAMLab/ORB_SLAM3#422]
mnFirstFrameId = 370
mnInitialFrameId = 353
228 Frames set to lost
First KF:17; Map init KF:12
New Map created with 148 points
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
Fail to track local map!
**Relocalized!!
TRACK_REF_KF: Less than 15 matches!!
Fail to track local map!
Creation of new map with id: 1
Exits current map 
Saved map with ID: 0
Creation of new map with last KF id: 23
[1]    42306 segmentation fault (core dumped)  rosrun orbslam3 mynteye_orbslam   false**

**Comment by davidlai0522** [comment]
Hi, do you have any solution for this? I faced the same issue. It only happens occasionally. I noticed that there is a high chance that it will happen when I am building a big map. When I tried to printed out the MapPoint pointer pMPi in Map.cc file Map::PreSave() function, I noticed that it will point to some weird address when the segmentation fault happens.
![Screenshot from 2022-09-01 15-32-59](https://user-images.githubusercontent.com/69185908/187858094-7c28e48a-a6ec-4180-acc5-ee710589bfea.png)
![Screenshot from 2022-09-01 15-33-18](https://user-images.githubusercontent.com/69185908/187858109-3f747c17-85df-4938-9888-8bd0238e63f1.png)
Notice the last pointer address before it fails. Do you have any idea about this?

**Comment by Suhao07** [comment]
bro how did you solve this problem?
