### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by knazneen123** [UZ-SLAMLab/ORB_SLAM3#430]
I have been trying to save monocular inertial map in binary .osa format and loading it again  but I am facing this exception- 
Floating point (core dumped).
Any idea why is this happening the same algorithm for saving and loading works for monocular slam perfectly and do map merging properly

I have referred this code for saving and loading map 
https://github.com/UZ-SLAMLab/ORB_SLAM3/pull/310

Following are the logs
_____________________________________________________________
Loading imagesLOADED!
Loading IMULOADED!

-------
Input sensor was set to: Monocular-Inertial

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Load File map/imutest3.osa
Starting to read the save binary file
End to load the save binary file
Camera in postload 0
Map id:0
Number of KF: 84
Number of MP: 5207
End to rebuild MapPoint references
End to rebuild KeyFrame references
Number KF:84; number MP:5207
Creation of new map with id: 1
Creation of new map with last KF id: 197
Seq. Name: LOADED SEQUENCE

Camera Parameters: 
- Camera: Pinhole
- fx: 572.512939453125
- fy: 596.432861328125
- cx: 321.779541015625
- cy: 244.67845153808594
- k1: 0.44454166293144226
- k2: -4.399817943572998
- p1: -0.0050515956245362759
- p2: -0.0031279937829822302
- k3: 11.516254425048828
- fps: 20
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 2000
- Scale Levels: 8
- Scale Factor: 1.2000000476837158
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Left camera to Imu Transform (Tbc): 
[-0.060808919, -0.99529386, 0.075447917, 0.00342225;
 -0.99772829, 0.0584139, -0.033556689, 0.0038737899;
 0.02899156, -0.077317066, -0.99658495, 0.0040304302;
 0, 0, 0, 1]

IMU frequency: 100 Hz
IMU gyro noise: 0.0015040205325931311 rad/s/sqrt(Hz)
IMU gyro walk: 3.723355257534422e-05 rad/s^2/sqrt(Hz)
IMU accelerometer noise: 0.017776371911168098 m/s^2/sqrt(Hz)
IMU accelerometer walk: 0.00056003581266850233 m/s^3/sqrt(Hz)
Not IMU data in mlQueueImuData!!
First KF:197; Map init KF:197
New Map created with 337 points
Point distribution in KeyFrame: left-> 337 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 0
14 Frames set to lost
First KF:201; Map init KF:197
New Map created with 169 points
Point distribution in KeyFrame: left-> 169 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2248
0 Frames set to lost
First KF:203; Map init KF:201
New Map created with 150 points
Point distribution in KeyFrame: left-> 150 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2317
0 Frames set to lost
First KF:206; Map init KF:203
New Map created with 155 points
Point distribution in KeyFrame: left-> 155 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2340
0 Frames set to lost
First KF:210; Map init KF:206
New Map created with 83 points
Point distribution in KeyFrame: left-> 83 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2377
0 Frames set to lost
First KF:213; Map init KF:210
New Map created with 91 points
Point distribution in KeyFrame: left-> 91 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2394
0 Frames set to lost
First KF:217; Map init KF:213
New Map created with 60 points
Point distribution in KeyFrame: left-> 60 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2466
0 Frames set to lost
First KF:219; Map init KF:217
New Map created with 186 points
Point distribution in KeyFrame: left-> 186 --- right-> 0
build optimization graph
scale too small
build optimization graph
IMU in Map 1 is initialized
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2491
0 Frames set to lost
First KF:231; Map init KF:219
New Map created with 145 points
Point distribution in KeyFrame: left-> 145 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2557
0 Frames set to lost
First KF:234; Map init KF:231
New Map created with 109 points
Point distribution in KeyFrame: left-> 109 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2621
0 Frames set to lost
First KF:237; Map init KF:234
New Map created with 171 points
Point distribution in KeyFrame: left-> 171 --- right-> 0
build optimization graph
IMU in Map 1 is initialized
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2633
0 Frames set to lost
First KF:249; Map init KF:237
New Map created with 148 points
Point distribution in KeyFrame: left-> 148 --- right-> 0
build optimization graph
IMU in Map 1 is initialized
start VIBA 1
build optimization graph
end VIBA 1
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2688
0 Frames set to lost
First KF:275; Map init KF:249
New Map created with 133 points
Point distribution in KeyFrame: left-> 133 --- right-> 0
TRACK_REF_KF: Less than 15 matches!!
Fail to track local map!
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2839
0 Frames set to lost
First KF:277; Map init KF:275
New Map created with 131 points
Point distribution in KeyFrame: left-> 131 --- right-> 0
build optimization graph
IMU in Map 1 is initialized
Not enough motion for initializing. Reseting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 2842
0 Frames set to lost
First KF:289; Map init KF:277
New Map created with 325 points
Point distribution in KeyFrame: left-> 325 --- right-> 0
build optimization graph
scale too small
build optimization graph
IMU in Map 1 is initialized
start VIBA 1
build optimization graph
end VIBA 1
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
*Merged detected
start VIBA 2
build optimization graph
end VIBA 2
*Merged detected
Merge detected!!!!
Check Full Bundle Adjustment
Request Stop Local Mapping
Local Mapping STOP
Local Map stopped
addVertex: FATAL, a vertex with ID 342 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1373 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1374 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1375 has already been registered with this graph
addVertex: FATAL, a vertex with ID 343 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1376 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1377 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1378 has already been registered with this graph
addVertex: FATAL, a vertex with ID 344 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1379 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1380 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1381 has already been registered with this graph
addVertex: FATAL, a vertex with ID 345 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1382 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1383 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1384 has already been registered with this graph
addVertex: FATAL, a vertex with ID 346 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1385 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1386 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1387 has already been registered with this graph
Floating point exception (core dumped)

**Comment by jdtardos** [comment]
Version 1.0 now includes map loading and saving operations
