### ISSUE TITLE
v1.0 release ros版本编译,提示找不到sophus库，及 Sophus::SE3f, cv::MAT,Eigen::Vector3f类型转换报错

### ISSUE THREAD

**Issue by oscar1780** [UZ-SLAMLab/ORB_SLAM3#442]
系统环境  ubuntu 18.04 , melodic, opencv4.0(本地编译 仅make 未make install,考虑兼容性问题未安装)
解决办法：
1、编译ros版本，需要将Examples_old文件夹下ROS文件夹复制到Examples文件夹下。将CMakeLists中用到OpenCV4的地方，连接到你的库位置。
2、将路径添加至~/.bashrc,这部分参考官方文档,运行./build.sh ./build_ros.sh
3、提示找不到sophus库，修改CMAKELISTS, include_directories中添加 ${PROJECT_SOURCE_DIR}/../../../Thirdparty/Sophus
4、Sophus::SE3f, cv::MAT,Eigen::Vector3f类型转换报错，应该是不能直接转换，不过可以换个办法，
  解决  cv::Mat Tcw = mpSLAM->TrackMonocular(cv_ptr->image,cv_ptr->header.stamp.toSec()); 报错
    cv::Mat Tcw;
    Sophus::SE3f  Tcw_SE3f = mpSLAM->TrackMonocular(cv_ptr->image,cv_ptr->header.stamp.toSec());
    Eigen::Matrix4f Tcw_Matrix = Tcw_SE3f.matrix();
    cv::eigen2cv(Tcw_Matrix, Tcw);
  解决 vPoints.push_back(pMP->GetWorldPos()); 报错
                  cv::Mat WorldPos;
                cv::eigen2cv(pMP->GetWorldPos(), WorldPos);
                vPoints.push_back(WorldPos);
  解决 cv::Mat Xw = pMP->GetWorldPos();报错
            cv::Mat Xw;
            cv::eigen2cv(pMP->GetWorldPos(), Xw);
再编译，没有其他问题的话正常编译通过。
5、回到 workspace目录下面 ，source下环境，rosrun ORB_SLAM3 Stereo_Inertial ./src/ORB_SLAM3/Vocabulary/ORBvoc.txt ./src/ORB_SLAM3/Examples_old/Stereo-Inertial/EuRoC.yaml true，就可以正常运行，新版本的yaml文件不知道为啥运行会报错，暂时未研究。

**Comment by knazneen123** [comment]
Are you facing this sophus error while running monocular inertial using ROS

Sophus ensure failed in function 'static Sophus::SO3<Scalar_> Sophus::SO3<Scalar_, Options>::expAndTheta(const Tangent&, Sophus::SO3<Scalar_, Options>::Scalar*) [with Scalar_ = float; int Options = 0; Sophus::SO3<Scalar_, Options>::Tangent = Eigen::Matrix<float, 3, 1>; Sophus::SO3<Scalar_, Options>::Scalar = float]', file '/home/../slam/projects/ORB_SLAM3_V1.0/Thirdparty/Sophus/sophus/so3.hpp', line 614.
SO3::exp failed! omega: -nan -nan -nan, real: -nan, img: -nan
??

**Comment by nindanaoto** [comment]
@knazneen123 You can use my code for the PR if you want.

**Comment by knazneen123** [comment]
Sure, are you not facing sophus error issue I mentioned earlier when you try to run Monocular-Inertial slam using ROS?

**Comment by nindanaoto** [comment]
I've just tested Stereo SLAM. If the error is Monocular specific one, I don't have any knowledge to add......

**Comment by BSSNBSSN** [comment]
That helps a lot, thank you very much!

**Comment by song-kun** [comment]
按照上述方法解决了  **cv::Mat Tcw = mpSLAM->TrackMonocular(cv_ptr->image,cv_ptr->header.stamp.toSec());**   报错以后，又出现了新的问题。

error: ‘eigen2cv’ is not a member of ‘cv’

所用的代码片段如下：
```cpp
void ImageGrabber::GrabImage(const sensor_msgs::ImageConstPtr& msg)
{
    // Copy the ros image message to cv::Mat.
    cv_bridge::CvImageConstPtr cv_ptr;
    try
    {
        cv_ptr = cv_bridge::toCvShare(msg);
    }
    catch (cv_bridge::Exception& e)
    {
        ROS_ERROR("cv_bridge exception: %s", e.what());
        return;
    }
    cv::Mat im = cv_ptr->image.clone();
    cv::Mat imu;

    cv::Mat Tcw;
    Sophus::SE3f Tcw_SE3f = mpSLAM->TrackMonocular(cv_ptr->image,cv_ptr->header.stamp.toSec());
    Eigen::Matrix4f Tcw_Matrix = Tcw_SE3f.matrix();
    cv::eigen2cv(Tcw_Matrix, Tcw);

    int state = mpSLAM->GetTrackingState();
    vector<ORB_SLAM3::MapPoint*> vMPs = mpSLAM->GetTrackedMapPoints();
    vector<cv::KeyPoint> vKeys = mpSLAM->GetTrackedKeyPointsUn();

    cv::undistort(im,imu,K,DistCoef);

    if(bRGB)
        viewerAR.SetImagePose(imu,Tcw,state,vKeys,vMPs);
    else
    {
        cv::cvtColor(imu,imu,CV_RGB2BGR);
        viewerAR.SetImagePose(imu,Tcw,state,vKeys,vMPs);
    }    
}
```

**Comment by song-kun** [comment]
> 
如果遇到这个问题（`error: ‘eigen2cv’ is not a member of ‘cv’`），加入三个头文件就可以了
```cpp
#include <Eigen/Dense>
#include <opencv2/core/eigen.hpp>
#include <opencv2/opencv.hpp>
```

**Comment by linClubs** [comment]
hi，compeled successfully，runros ORB_SLAM3 Mono 
Input sensor was set to: Monocular
段错误 (核心已转储)
How to deal with it？

**Comment by song-kun** [comment]
For me, this is due to that when building ROS part, OpenCV4 is used, which is different from no ROS part (use Opencv3).
You can just change the CMakeLists.txt in ROS part to force it linked to Opencv3.

**Comment by lhyakn** [comment]
> hi，compeled successfully，runros ORB_SLAM3 Mono Input sensor was set to: Monocular 段错误 (核心已转储) How to deal with it？

Did you fix this problem, I have the same problem as you...

**Comment by linClubs** [comment]
no solve。are u a stduents？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月21日(星期四) 晚上9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [UZ-SLAMLab/ORB_SLAM3] v1.0 release ros版本编译,提示找不到sophus库，及 Sophus::SE3f, cv::MAT,Eigen::Vector3f类型转换报错 (Issue #442)





  
hi，compeled successfully，runros ORB_SLAM3 Mono Input sensor was set to: Monocular 段错误 (核心已转储) How to deal with it？
  
Did you fix this problem, I have the same problem as you...

**Comment by lhyakn** [comment]
> no solve。are u a stduents？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月21日(星期四) 晚上9:31 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [UZ-SLAMLab/ORB_SLAM3] v1.0 release ros版本编译,提示找不到sophus库，及 Sophus::SE3f, cv::MAT,Eigen::Vector3f类型转换报错 (Issue #442) hi，compeled successfully，runros ORB_SLAM3 Mono Input sensor was set to: Monocular 段错误 (核心已转储) How to deal with it？ Did you fix this problem, I have the same problem as you... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

对,我现在还是学生. 我解决这个问题了,是我这里ROS-neotic-cv_bridge的OpenCV版本的问题,我卸载了cv_bridge后,从github重新下载并编译安装cv_bridge问题就解决了,希望可以帮到你

**Comment by linClubs** [comment]
有链接教程么。谢谢了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月23日(星期六) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [UZ-SLAMLab/ORB_SLAM3] v1.0 release ros版本编译,提示找不到sophus库，及 Sophus::SE3f, cv::MAT,Eigen::Vector3f类型转换报错 (Issue #442)





  
no solve。are u a stduents？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年4月21日(星期四) 晚上9:31 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [UZ-SLAMLab/ORB_SLAM3] v1.0 release ros版本编译,提示找不到sophus库，及 Sophus::SE3f, cv::MAT,Eigen::Vector3f类型转换报错 (Issue #442) hi，compeled successfully，runros ORB_SLAM3 Mono Input sensor was set to: Monocular 段错误 (核心已转储) How to deal with it？ Did you fix this problem, I have the same problem as you... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
对,我现在还是学生. 我解决这个问题了,是我这里ROS-neotic-cv_bridge的OpenCV版本的问题,我卸载了cv_bridge后,从github重新下载并编译安装cv_bridge问题就解决了,希望可以帮到你

**Comment by cpymaple** [comment]
> 

hi, I face this problem, but I do not know how to solve it. Could you please help me?

**Comment by Kin-Zhang** [comment]
我做了一个20.04的repo 直接clone就能跑，如果ROS没问题的话哈 [I fork with creating new repo for 20.04 and noetic for ORB_SLAM3 based the discussion here. You can check the commit and diff to see those modification to adapt noetic]
https://github.com/Kin-Zhang/ORB_SLAM3/tree/feat/20.04
更为具体的教程可以看：https://blog.csdn.net/qq_39537898/article/details/124775247

```bash
git clone -b feat/20.04 https://github.com/kin-zhang/ORB_SLAM3.git
cd ORB_SLAM3
chmod +x build.sh
./build.sh

# ---- examples 
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/home/kin/workspace/ORB_SLAM3/Examples_old/ROS
chmod +x build_ros.sh
./build_ros.sh

```

不过我感觉imu问题在自己数据集上搞不定了... 不知道为啥

**Comment by meng152634** [comment]
> hi，compeled successfully，runros ORB_SLAM3 Mono Input sensor was set to: Monocular 段错误 (核心已转储) How to deal with it？

@linClubs @lhyakn this error can be fixed by delete the `-march=native`  option in the CMakeLists.txt file located in the ROS/ORB_SLAM3, Thirdarty/DBoW2, and Thirdarty/g2o. and then recompile
