### ISSUE TITLE
Why is the accuracy getting worse ?

### ISSUE THREAD

**Issue by chennuo0125-HIT** [UZ-SLAMLab/ORB_SLAM3#487]
![diff](https://user-images.githubusercontent.com/37269147/153143489-a482741b-3c86-4f72-9a53-e80b7c6fda14.png)

from above picture captured from paper, in stereo mode, ORB_SLAM2 get better accuracy than ORB_SLAM3, What changes in ORB_SLAM3 lead to this result ?

**Comment by JaySlamer** [comment]
> ![diff](https://user-images.githubusercontent.com/37269147/153143489-a482741b-3c86-4f72-9a53-e80b7c6fda14.png)
> 
> from above picture captured from paper, in stereo mode, ORB_SLAM2 get better accuracy than ORB_SLAM3, What changes in ORB_SLAM3 lead to this result ?

You can clearly see from the table that ORB_SLAM2 failed to finish the last data sequence but ORB_SLAM3 succeeded with a low accuracy. So the accuracy of ORB_SLAM2 does not include the result from last sequence. that is why its accuracy are marked with a * sign.

**Comment by chennuo0125-HIT** [comment]
> > ![diff](https://user-images.githubusercontent.com/37269147/153143489-a482741b-3c86-4f72-9a53-e80b7c6fda14.png)
> > from above picture captured from paper, in stereo mode, ORB_SLAM2 get better accuracy than ORB_SLAM3, What changes in ORB_SLAM3 lead to this result ?
> 
> You can clearly see from the table that ORB_SLAM2 failed to finish the last data sequence but ORB_SLAM3 succeeded with a low accuracy. So the accuracy of ORB_SLAM2 does not include the result from last sequence. that is why its accuracy are marked with a * sign.
