### ISSUE TITLE
Examples runners (eg: ./tum_vi_examples) are missing

### ISSUE THREAD

**Issue by migranram** [UZ-SLAMLab/ORB_SLAM3#495]
The example runners are missing or I am not able to find them. Anyone knows how to run any demo, for example TUM?  I would like to know if everything is installed and working correclty.

**Comment by JohnN193** [comment]
some of the codes in the Examples have a line for what to pass into the code. 
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Examples/Stereo/stereo_tum_vi.cc#L47

for the euroc_examples.sh and similar scripts they mentioned i pulled them from some older commits/repos, like here https://github.com/UZ-SLAMLab/ORB_SLAM3/tree/def2d2d97d1c1ecabdd5725aa76b658b05fce4c8

**Comment by zhaodejian** [comment]
> some of the codes in the Examples have a line for what to pass into the code. https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Examples/Stereo/stereo_tum_vi.cc#L47
> 
> for the euroc_examples.sh and similar scripts they mentioned i pulled them from some older commits/repos, like here https://github.com/UZ-SLAMLab/ORB_SLAM3/tree/def2d2d97d1c1ecabdd5725aa76b658b05fce4c8

so we can get euroc_examples.sh form the old one? and then runing in our computer?

**Comment by migranram** [comment]
Yes, with some modifications you can still run them. The ROS examples work as well. You can find them in the old examples folder. You may need to change something in the CMakeLists.

**Comment by mamdouhmostafa** [comment]
> 

Can you explain what needs to be changed to run these files again?
