### ISSUE TITLE
No ROS/ORB SLAM3 found under Example

### ISSUE THREAD

**Issue by ShinChoon** [UZ-SLAMLab/ORB_SLAM3#516]
I found that there is no ROS/ORB_SLAM3 in Example but in Example_old, could you please update the instructions in README? Thanks

**Comment by RanceGru** [comment]
You need to put example_ Old's ROS soft link to example

**Comment by JaimeParker** [comment]
or just re-edit the `build_ros.sh` file

**Comment by ShinChoon** [comment]
Thank you for reply, I knew these already because I accidently found a Chinese blogger mentioned it. But I didn't see any other similar answer before. So I raised this issue and hope it can be displayed if other others try to google it.
