### ISSUE TITLE
poor evaluation on mono

### ISSUE THREAD

**Issue by lihzh233** [UZ-SLAMLab/ORB_SLAM3#518]
I tried the evaluation scripts in mono model with MH01 and V101. It seems not good.
`python evaluation/evaluate_ate_scale.py evaluation/Ground_truth/EuRoC_left_cam/MH01_GT.txt CameraTrajectory.txt --plot MH01_mono.pdf`
the result is `2.549304,2.436262,0.021201`
Is that normal?

**Comment by lihzh233** [comment]
I figure it out by changing the evaluation scripts with the ones used in ORB-SLAM2.

**Comment by TPODAvia** [comment]
@lihzh233 How and where did you changed if evaluation scripts?
