### ISSUE TITLE
TUM_1024  Monocular-Inertial Loop closing not work

### ISSUE THREAD

**Issue by zazgf** [UZ-SLAMLab/ORB_SLAM3#533]
@jdtardos Hi,Mr Juan D. Tardos.I just runned the TUM_1024  Monocular-Inertial example with the latest version. I found the loop closing not worked as expected, and I don't know why. Can you help me？
![Screenshot from 2022-03-30 13-49-48](https://user-images.githubusercontent.com/49219511/160760476-7e3ac945-4660-42b1-9403-a693b2e7ec78.png)

**Comment by jdtardos** [comment]
You need at least 3 keyframes that see areas in common. Please, read the
ORB-SLAM3 paper.

Juan D. Tardos

**Comment by zazgf** [comment]
@jdtardos Mr Juan D. Tardos, thanks for your advice. I will read the ORB_SLAM3 paper and try to understand this problem.

**Comment by zazgf** [comment]
@jdtardos  Prof. Tardos, I have read the ORB_SLAM3 paper, and now I know your meaning , Thanks again!
