### ISSUE TITLE
How to save and load map?

### ISSUE THREAD

**Issue by JACKLiuDay** [UZ-SLAMLab/ORB_SLAM3#535]
Hi, thank you for your great work about ORB_SLAM3 V1.0.!
I tried to read the calibration pdf carefully. And I want to save the map for localization with my quadruped robot. After  I enter the Atlas param in the .yaml profile. It did not work and showed segmentation fault. And I didn't see any map in the file. So how to save the map int ORB_SLAM3 v1.0. I need some help.
  
![image](https://user-images.githubusercontent.com/30967867/161008481-7ea1e1bb-a621-40f2-8a3e-8ec779b1ce52.png)

**Comment by JACKLiuDay** [comment]
![image](https://user-images.githubusercontent.com/30967867/161014635-5aae6f6a-e32e-42f8-a94f-fb4e6ff49d9d.png)
I tried the .yaml with mono-inertial again. It did not show segmentation fault like the stereo-inertial. And I saved the map successfully. But when I load the map.osa. It shows errors.
![image](https://user-images.githubusercontent.com/30967867/161019782-15b2d0d4-8e69-48e0-adad-e4b5f1aaf183.png)
And when I save the map it show some errors.

**Comment by JACKLiuDay** [comment]
![image](https://user-images.githubusercontent.com/30967867/163085944-a006f9d3-3385-4b60-8c65-31f589f737e5.png)
Sometimes when I try to shutdown system and save atlas map, it often segmentation fault without map saved.
![image](https://user-images.githubusercontent.com/30967867/163086146-32a8c068-6cc7-411e-a4d6-b2bdb36f8b47.png)
It looks like something wrong with mpLocalMapper->RequestFinish(); mpLoopCloser->RequestFinish(); these two functions.

https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/443

I tried with issues/443 and it still have seg fault. So maybe the save/load function in orb slam3 do not work well.

**Comment by mascomen4** [comment]
Hey. As far as I know Save and Load functionality is still a bit buggy. It was working for me on some sequences on the KITTI dataset, but for some of them not.  
 
But there is the thing I noticed: If you're using monocular mode, the map changes significantly during the processing, so I got a lot of errors with load and saving of the Atlas on KITTI dataset in this mode. Please try to use the mode which has a scalar metric: either **mono-inertial**, either **stereo** mode

Also, I suspect they didn't write a code yet for loading the data required for Localization mode from the loaded .osa Atlas

**Comment by JACKLiuDay** [comment]
> Hey. As far as I know Save and Load functionality is still a bit buggy. It was working for me on some sequences on the KITTI dataset, but for some of them not.
> 
> But there is the thing I noticed: If you're using monocular mode, the map changes significantly during the processing, so I got a lot of errors with load and saving of the Atlas on KITTI dataset in this mode. Please try to use the mode which has a scalar metric: either **mono-inertial**, either **stereo** mode
> 
> Also, I suspect they didn't write a code yet for loading the data required for Localization mode from the loaded .osa Atlas

Yes,  I got similar test results to you.

**Comment by hxlei0827** [comment]
> Hi, thank you for your great work about ORB_SLAM3 V1.0.! I tried to read the calibration pdf carefully. And I want to save the map for localization with my quadruped robot. After I enter the Atlas param in the .yaml profile. It did not work and showed segmentation fault. And I didn't see any map in the file. So how to save the map int ORB_SLAM3 v1.0. I need some help.
> 
> ![image](https://user-images.githubusercontent.com/30967867/161008481-7ea1e1bb-a621-40f2-8a3e-8ec779b1ce52.png)

hi, may i know how did you find the .osa file? 
I add          System.LoadAtlasFromFile: "test.osa" in Asus.yaml, but I cannot find any .osa file after running.
Thanks in advance

**Comment by wengchenyang1** [comment]
> > Hi, thank you for your great work about ORB_SLAM3 V1.0.! I tried to read the calibration pdf carefully. And I want to save the map for localization with my quadruped robot. After I enter the Atlas param in the .yaml profile. It did not work and showed segmentation fault. And I didn't see any map in the file. So how to save the map int ORB_SLAM3 v1.0. I need some help.
> > ![image](https://user-images.githubusercontent.com/30967867/161008481-7ea1e1bb-a621-40f2-8a3e-8ec779b1ce52.png)
> 
> hi, may i know how did you find the .osa file? I add System.LoadAtlasFromFile: "test.osa" in Asus.yaml, but I cannot find any .osa file after running. Thanks in advance

Sometimes the .osa file is not saved if segmentation fault occurs during saving. 

[This](https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/443#issuecomment-1154814254) seems to be a solution.

**Comment by kenhuang1964** [comment]
Hey @JACKLiuDay, did you end up figuring out how to load and save maps? I am trying to localize the camera within a saved map. Can you please help me?

**Comment by JACKLiuDay** [comment]
> Hey @JACKLiuDay, did you end up figuring out how to load and save maps? I am trying to localize the camera within a saved map. Can you please help me?

Hi, sorry bro. I am using lidar SLAM for my project now. I did not use ORB SLAM3 for a long time.  And I tried to use the map system but got nothing.

**Comment by ThakurSarveshGit** [comment]
> Hey @JACKLiuDay, did you end up figuring out how to load and save maps? I am trying to localize the camera within a saved map. Can you please help me?

Hi, to simply save a map uncomment the file save param in corresponding .YAML file:

For ex: EuRoC.yaml has these params:
```
# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
System.LoadAtlasFromFile: "Session_MH01Mono"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01Mono"
```

I ran evaluation_example.sh, first time with save param uncommented and next time with loadFile command uncommented and it was able to save and load file respectively.

**Comment by kenhuang1964** [comment]
> > Hey @JACKLiuDay, did you end up figuring out how to load and save maps? I am trying to localize the camera within a saved map. Can you please help me?
> 
> Hi, to simply save a map uncomment the file save param in corresponding .YAML file:
> 
> For ex: EuRoC.yaml has these params:
> 
> ```
> # If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
> System.LoadAtlasFromFile: "Session_MH01Mono"
> 
> # The store file is created from the current session, if a file with the same name exists it is deleted
> #System.SaveAtlasToFile: "Session_MH01Mono"
> ```
> 
> I ran evaluation_example.sh, first time with save param uncommented and next time with loadFile command uncommented and it was able to save and load file respectively.

Thank you!

**Comment by BeenToJupiter** [comment]
> > Hey @JACKLiuDay, did you end up figuring out how to load and save maps? I am trying to localize the camera within a saved map. Can you please help me?
> 
> Hi, to simply save a map uncomment the file save param in corresponding .YAML file:
> 
> For ex: EuRoC.yaml has these params:
> 
> ```
> # If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
> System.LoadAtlasFromFile: "Session_MH01Mono"
> 
> # The store file is created from the current session, if a file with the same name exists it is deleted
> #System.SaveAtlasToFile: "Session_MH01Mono"
> ```
> 
> I ran evaluation_example.sh, first time with save param uncommented and next time with loadFile command uncommented and it was able to save and load file respectively.

None of the .yaml files have any commented lines for that. What and where am I missing?

**Comment by BeenToJupiter** [comment]
> > Hey @JACKLiuDay, did you end up figuring out how to load and save maps? I am trying to localize the camera within a saved map. Can you please help me?
> 
> Hi, to simply save a map uncomment the file save param in corresponding .YAML file:
> 
> For ex: EuRoC.yaml has these params:
> 
> ```
> # If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
> System.LoadAtlasFromFile: "Session_MH01Mono"
> 
> # The store file is created from the current session, if a file with the same name exists it is deleted
> #System.SaveAtlasToFile: "Session_MH01Mono"
> ```
> 
> I ran evaluation_example.sh, first time with save param uncommented and next time with loadFile command uncommented and it was able to save and load file respectively.

I added a file address for the save parameter, and it says that the binary files is saved to the given address but I am not able to find the file. What could be the issue? I do not see any seg fault.

**Comment by tianyilim** [comment]
If anyone is still stuck on this in 2025 (maybe look at a better-implemented library? 😉) , this may help:

https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/882#issuecomment-3341706147
