### ISSUE TITLE
Error when build Sophus and building ORB_SLAM3

### ISSUE THREAD

**Issue by hafidh561** [UZ-SLAMLab/ORB_SLAM3#545]
Hy guys, when i build ORB_SLAM3 in Ubuntu 20.04 and ROS Noetic, i get some error in specific for build Sophus and ORB_SLAM3 like this. 
```
error This compiler appears to be too old to be supported by Eigen
```

**Comment by dandingol03** [comment]
@hafidh561 HI, i met the same problem. How do you fix this
