### ISSUE TITLE
"terminate called after throwing an instance of 'cv::Exception'" occurs after "BoW: xxx matches between xxx points with coarse Sim3"

### ISSUE THREAD

**Issue by qliao001** [UZ-SLAMLab/ORB_SLAM3#58]
I have tried the Monocular version with customized streaming sequences, which worked well with ORB-SLAM2. However, with ORB-SLAM3, for some sequences, whenever "BoW: xxx matches between xxx points with coarse Sim3" occurs, the system throws a cv exception as below:

> BoW: 276 matches between 635 points with coarse Sim3
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.4.0-pre) /home/qi/opencv_build/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
Aborted (core dumped)

I can confirm that the file exists and is not corrupted. By printing the loaded image, we can see that the exception may happen at different frame ids of the same sequence and the image was loaded successfully in mono_euroc.cc. I assume it might be a cvtColor exception in LoopClosing.cc? Please find in below **two error printings** when running the **same** sequence:

![Screenshot from 2020-08-13 10-33-31](https://user-images.githubusercontent.com/6739476/90112617-85cabd00-dd50-11ea-8d55-88d2f90df9d3.png)

![Screenshot from 2020-08-13 10-43-55](https://user-images.githubusercontent.com/6739476/90113630-edcdd300-dd51-11ea-826d-a25483669953.png)

**Comment by ccamposm** [comment]
Hi @qliao001, are you working with the latest version of ORB-SLAM3? This error should have been solved

**Comment by qliao001** [comment]
> Hi @qliao001, are you working with the latest version of ORB-SLAM3? This error should have been solved

Right! updated to the latest version, problem solved!! Thank you so much!!
