### ISSUE TITLE
SLAM trajectory in real world

### ISSUE THREAD

**Issue by spiec** [UZ-SLAMLab/ORB_SLAM3#582]
I'm testing ORB-SLAM on my drone videos, using monocular camera - thus, there is no easy way to derive information about the scale. However, during flight I've quite precise information about the drone's altitude (in meters), from other sources.

Of course, trajectory generated by the SLAM algorithm is given in its own coordinate system.
What I'd like to see is the real (X, Y, Z) position of the drone.

In principle, having information about the altitude (or Z), for each time step, gives me possibility to find relation between Z_slam and Z_real_world (e.g. scale_factor = Z_real_world / Z_slam ?).

How sensible is using this scaling factor to convert remaining coordinates (X, Y) to the real-world ones?

**Comment by ihorironman** [comment]
@spiec are you solve?
