### ISSUE TITLE
How to get the real depth of MapPoints in Mono mode?

### ISSUE THREAD

**Issue by Sherlock-hh** [UZ-SLAMLab/ORB_SLAM3#596]
When I use the mono mode to track, I found code like this:

```
float medianDepth = pKFini->ComputeSceneMedianDepth(2);
    float invMedianDepth;

    if(mSensor == System::IMU_MONOCULAR)
        invMedianDepth = 4.0f/medianDepth; // 4.0f
    else
        invMedianDepth = 1.0f/medianDepth;

    if(medianDepth<0 || pKFcur->TrackedMapPoints(1)<30) // TODO Check, originally 100 tracks
    {
        Verbose::PrintMess("Wrong initialization, reseting...", Verbose::VERBOSITY_NORMAL);
        mpSystem.ResetActiveMap();
        return;
    }

    // Scale initial baseline
    cv::Mat Tc2w = pKFcur->GetPose();
    Tc2w.col(3).rowRange(0,3) = Tc2w.col(3).rowRange(0,3)*invMedianDepth;
    pKFcur->SetPose(Tc2w);

    // Scale points
    vector<std::shared_ptr<MapPoint>> vpAllMapPoints = pKFini->GetMapPointMatches();
    for(size_t iMP=0; iMP<vpAllMapPoints.size(); iMP++)
    {
        if(vpAllMapPoints[iMP])
        {
            std::shared_ptr<MapPoint> pMP = vpAllMapPoints[iMP];
            pMP->SetWorldPos(pMP->GetWorldPos()*invMedianDepth);
            pMP->UpdateNormalAndDepth();
        }
    }
```
It's seems to change  all the MapPoint's depth to 1, like this:
Before plus invMedianDepth:
`[2.6153, 0.01781, 31.410089 ]`
After:
`[0.08196, 2.2e-03, 0.9822]`

 I don't understand why to do this,  because I can sure the point's true depth is more than 3 meters, dosen't this will make some error to the MapPoint trangulation and pose optimizition? I want to get the true pose of MapPoint, the before pos `[2.6153, 0.01781, 31.410089 ]` ‘s depth`  31.410089 ` seems too far for meters, is that CM？

I don't know if my data are right, looking for your reply, thank you very much!

**Comment by Waterfly222** [comment]
In monocular you don't have the scale of you map because you don't have any depth knowledge so you'll never have your results in meters but on a arbitrary unit.
If you want to compare multiple results you need to rescale them to be at the same scale (I use the python package evo by Michael Grupp to do so)
I could be wrong though, I'm only a beginner in SLAM.

**Comment by Sherlock-hh** [comment]
> 

It's so frustrated, I save the MapPoints yesterday，all of my features are in a plane, but the MapPoints it‘s even can’t find a plane. I'll try some way to solve it, thank you for u reply~!

**Comment by Sherlock-hh** [comment]
aha I find the better way to get the better MapPoints if there in a plane,  just change the construct way to:
`thread threadH(&TwoViewReconstruction::FindHomography, this, ref(vbMatchesInliersH), ref(SH), ref(H));`
 the Homography is better than Fundamental matrix if the features are in a plane

**Comment by lcc157** [comment]
Do you know why it needs to be invMedianDepth = 4.0f/medianDepth , and this constant  (4.0f) is set according to what?

**Comment by Sherlock-hh** [comment]
> 

it's means to set the average depth of mappoints to 4, because mono mode dosen't has the real scale of ture world, so u can set a average depth when the map is initialize, offer the map a scale first, it's been so long, i just remenber somewhere in code has set the mappoint'depth to 0~1, u can check the output of mappoint after initialized, the depth is around 4.

**Comment by lcc157** [comment]
Thanks!

**Comment by NJNischal** [comment]
Hello @Sherlock-hh , we’re you able to achieve real depth? Also, did you remove the scaling of the algorithm for your purpose? Thank you!
