### ISSUE TITLE
Will docker image be released?

### ISSUE THREAD

**Issue by mengzhibin** [UZ-SLAMLab/ORB_SLAM3#60]
Will docker image be released?

**Comment by ccamposm** [comment]
We are not currently planning to work a docker image. However, we welcome any work from the comunity

**Comment by jahaniam** [comment]
Hi guys, I have written a docker for ros melodic if you are interested.

https://github.com/jahaniam/orbslam3_docker

**Comment by LMWafer** [comment]
Here is a docker image ready for Realsense cameras. Documentation will come very soon !

https://hub.docker.com/r/lmwafer/orb-slam-3-ready
