### ISSUE TITLE
Why is there no IMU in the rgbd mode?

### ISSUE THREAD

**Issue by xiehousen** [UZ-SLAMLab/ORB_SLAM3#618]
ORB-SLAM3 only supports monocular/stereo visual inertial SLAM or RGB-D SLAM. 
Why does RGBD mode not support IMU ? 
If both monocular and stereo cameras support IMU, should it also be possible to add IMU support to RGBD mode?

Thanks in advance.

**Comment by liyuting-123** [comment]
> ORB-SLAM3 only supports monocular/stereo visual inertial SLAM or RGB-D SLAM. Why does RGBD mode not support IMU ? If both monocular and stereo cameras support IMU, should it also be possible to add IMU support to RGBD mode?
> 
> Thanks in advance.

hi，I have the same problem, have you implemented the RGBD-IMU model to run in ORB-SLAM3? Thx.
