### ISSUE TITLE
Sophus fails to build on Raspberry Pi

### ISSUE THREAD

**Issue by piran-prog** [UZ-SLAMLab/ORB_SLAM3#633]
Hi,
I'm trying to get this working on a raspberry pi 4 (without ROS) but it fails when trying to build sophus:
![sophus](https://user-images.githubusercontent.com/75266063/185643777-b67543c1-caa3-4e3a-a9b8-a9fc2ce91eae.png)

It get's this far then just sits there locking up the whole machine.

**Comment by piran-prog** [comment]
It did work through in the end but failed with an error 2
![sophus2](https://user-images.githubusercontent.com/75266063/185653723-86f2b953-79c0-4860-bd1f-b56299b3cc1d.png)

**Comment by SvenDC** [comment]
Might be because you run out of RAM? The system just locking up hints at it at least.
Try adding -j1 to your build command. This will limit the amount of jobs it runs concurrently and might be enough to get it to build.

**Comment by piran-prog** [comment]
Brilliant thanks.
That got the sophus to build.
Unfortunately it looks like it's running out of RAM and crashing cc1plus at optimiser.c now

**Comment by piran-prog** [comment]
looks like it's the same as issue  #327

**Comment by piran-prog** [comment]
Fixed It.
It was a memory issue. Setting the -j1 in the build.sh helped. The default swap on the Pi is 100MB - I expanded this to 2GB and it has now compiled.

**Comment by Taoran2023** [comment]
hi, did you successfully run ORBSLAM3 on Pi4?

**Comment by piran-prog** [comment]
Sort of. Yes I got it running but only through ROS, the performance was very poor and if the loop closing thread kicked off it took so much resources it effectively lost localisation.

**Comment by Taoran2023** [comment]
good to hear!  I'm trying to run orbslam3 mono-inertial test base on pi4.
