### ISSUE TITLE
When pMP->mbTrackInView boolean flag gets set to True

### ISSUE THREAD

**Issue by Mechazo11** [UZ-SLAMLab/ORB_SLAM3#646]
Hi,

When studying the `int ORBmatcher::SearchByProjection(Frame &F, const vector<MapPoint*> &vpMapPoints, const float th, const bool bFarPoints, const float thFarPoints);` method form the` ORBmatcher.cc`, an important variable seems to be the `MapPoint::mbTrackInView` boolean variable for each of the MapPoint objects.

From `Tracking.cc`, it seems this variable is always set to False and even in `MapPoint.cc`, this variable is always initialized as 'False'. I tried to look for where this flag gets set to True for a MapPoint object but could not find it so far.
   
My question is, where does the `MapPoint::mbTrackInView` value gets set to `True`?

Thanks
@Mechazo11

**Comment by richard-elvira** [comment]
Hi, 

It may appear that the variable is not used, but it is set to true in `Frame::isInFrustum`
