### ISSUE TITLE
Different results of running orbslam3 on the same data set

### ISSUE THREAD

**Issue by lishanggui** [UZ-SLAMLab/ORB_SLAM3#68]
Hi many thanks for the great contribution!  After running my own recorded data experiment on orbslam3 many times (stereo-only experience), the map results obtained by using the evo tool to analyze are different. What is the reason for this (multi-threading will have a certain impact on the selection of key frames)? Does this belong to the normal error range? I got the same conclusion in orb-slam2.
![image1](https://user-images.githubusercontent.com/58578789/90485946-d5532380-e16a-11ea-8e10-f85f0e36eb83.png)

**Comment by jdtardos** [comment]
Yes, you are right, ORB-SLAM3 has random behaviour, giving different results in different executions of the same dataset. You can see it clearly in figure 4 in the ORB-SLAM3 paper: https://arxiv.org/pdf/2007.11898.pdf
I think the differences you show in your results are normal.

I believe there are two main sources of randomness:
1) The use of random number generators in RANSAC.
2) The unpredictable interleaving of Tracking, Mapping, and Loop Closing threads, that depends on the operating system scheduler. This unpredictability makes that in different executions the estimated Keyframe poses may differ, or even different frames can be chosen as keyframes.
