### ISSUE TITLE
IMU  refine scale

### ISSUE THREAD

**Issue by sandstorm666** [UZ-SLAMLab/ORB_SLAM3#692]
I used the relative depth map in rgbd+imu, but I found that the scale in LocalMapping.cc is always 1. I magnify the value of the relative depth map by 10 times, but the scale is still 1.

**Comment by sandstorm666** [comment]
I sloved.

**Comment by S0UL4** [comment]
Hi,
Did you please use relocalization mode with rgbd+imu or mono+imu ? because i coudln't relocalize with previously loaded map..
Thanks
