### ISSUE TITLE
ReconstructH

### ISSUE THREAD

**Issue by sandstorm666** [UZ-SLAMLab/ORB_SLAM3#695]
In TwoViewReconstruction::ReconstructH  function 'vP3D=bestP3D' is missed?

**Comment by zeal-up** [comment]
@sandstorm666 Hi,I also noticed this bug(it is a bug?). Why did you closed this issue?

**Comment by chunxiaoqiao** [comment]
@sandstorm666 Is this a bug? I'm encountering the same issue.
