### ISSUE TITLE
How to solve this error produced during make 

### ISSUE THREAD

**Issue by HanochZzhou** [UZ-SLAMLab/ORB_SLAM3#7]
Hi, Thanks for sharing your great work. And I met some errors when I used 'make -j8' to build the project.
It output like below:
ORB_SLAM3/include/Map.h:140:33: error: ‘list’ has not been declared
     void printReprojectionError(list<KeyFrame*> &lpLocalWindowKFs, KeyFrame* mpCurrentKF, string &name, string &name_folder);
                                 ^
/ORB_SLAM3/include/Map.h:140:37: error: expected ‘,’ or ‘...’ before ‘<’ token
     void printReprojectionError(list<KeyFrame*> &lpLocalWindowKFs, KeyFrame* mpCurrentKF, string &name, string &name_folder);

All the dependencies have been installed correctly.

I am really confused by the errors and hope someone could help me!

**Comment by jjgr3496** [comment]
Hi @HanochZzhou, unfortunately I cannot reproduce your error (likely due to different compilers). In any case, you can try to add the name space std:: whenever you find an error like yours to make sure the compiler searches for the correct class.
