### ISSUE TITLE
What is this ORB vocabulary about?

### ISSUE THREAD

**Issue by choffmann** [UZ-SLAMLab/ORB_SLAM3#70]
As the title says, I couldn't figure out what the purpose of this ORB vocabulary is? 

Do I have to tune it at some point?

**Comment by jdtardos** [comment]
ORB-SLAM uses a Bag-of-Words place recognition technique for relocation and loop closing. The vocabulary is used to convert a set of features into a set of visual words. You don't need to tune it, the provided vocabulary works nicely in all environments. For more details, see: 
Dorian Gálvez-López and Juan D. Tardós. Bags of Binary Words for Fast Place Recognition in Image Sequences. IEEE Transactions on Robotics, vol. 28, no. 5, pp. 1188-1197, 2012.
