### ISSUE TITLE
DBoW thread safety and controllable random behaviour

### ISSUE THREAD

**Issue by jskinn** [UZ-SLAMLab/ORB_SLAM3#71]
ORB-SLAM2 gives a different answer every time you run it on linux (as it should, it uses RANSAC), but you cannot control the random behavior through the seed.
As far as I can tell, ORB-SLAM3 has inherited this issue (and since this is where the active development is, this is where I submit the issue)

The problem arises from the use of the DBoW Random.h library to manage random state.
If you look at `Thirdparty/DBoW2/DUtils/Random.cpp`, you can see that it is mostly just a wrapper around std::rand and std::srand.
According to the [documentation](https://en.cppreference.com/w/cpp/numeric/random/rand), it is implementation-defined as to whether std::rand is thread safe, and on all linux platforms, it is not (not sure about windows).
The result is that in different runs, the threads access the shared PRNG state in different order, leading to diverging behavior.

The recommended solution is to use the new C++11 random generators to manage a separate random state for each thread, see [https://en.cppreference.com/w/cpp/numeric/random](https://en.cppreference.com/w/cpp/numeric/random).

The requisite changes are, as far as I can see:
- Remove all usages of `DBoW::Random`
- Create separate `std::default_random_engine` objects in `ORB_SLAM3::Tracking` and `ORB_SLAM3::LoopClosing' (I'm not sure if any of the other threads use a PRNG, but if so, they should have their own random engine)
- Seed the `std::default_random_engine` objects with a common initial seed, perhaps read from the configuration?
- Pass those engine objects into the `ORB_SLAM3::Sim3Solver` and `ORB_SLAM3::MLPnPSolver` constructors or into `iterate`.
- Use `std::uniform_int_distribution` wherever `DBoW::Random::RandomInt` was used.

This should allow ORB_SLAM3 to give reproducible results on standard datasets.

**Comment by jdtardos** [comment]
Thanks for your suggestion. Yes, you are right, ORB-SLAM2 and ORB-SLAM3 have random behaviour, giving different results in different executions of the same dataset. You can see it clearly in figure 4 in the ORB-SLAM3 paper: https://arxiv.org/pdf/2007.11898.pdf

I believe there are two main sources of randomness:
1) The use of random number generators. The solution you propose will probably eliminate this one.
2) The unpredictable interleaving of Tracking, Mapping, and Loop Closing threads, that depends on the operating system scheduler. This unpredictability makes that in different executions the estimated Keyframe poses may differ, or even different frames can be chosen as keyframes.

I believe that the second source is more important than the first one. For solving it you would need to use thread priorities and a real-time operating system, and remove other interfering processes from your system. Not easy.

Please, if you try your approach, let us know how much does it improve repeatability.
