### ISSUE TITLE
Alignment and rescale of trajectories in EuRoC dataset

### ISSUE THREAD

**Issue by squaresoft2015** [UZ-SLAMLab/ORB_SLAM3#73]
The generated trajectories have different number of poses with ground truth. For example, ORB-SLAM3 generates 2674 poses in monocular mode and 2700 poses in stereo mode. But the officially provided dataset contains 26302 poses in ground truth file. How can I align the estimated poses with ground truth? I tried -va parameter but it promots: 
`[ERROR] found no matching timestamps between reference and f_dataset-V101_mono.txt with max. time diff 0.01 (s) and time offset 0.0 (s)`
Any help? Thanks

**Comment by richard-elvira** [comment]
ORBSLAM3 only reports the trajectory at frame level, that means we only obtain the pose when an image exists. In the other hand, EuRoc provides a GT with other measure devices, in Machine Hall uses Leica and in Vicon Room an OptiTrack. For that reason the amount of poses is not the same.

**Comment by squaresoft2015** [comment]
> ORBSLAM3 only reports the trajectory at frame level, that means we only obtain the pose when an image exists. In the other hand, EuRoc provides a GT with other measure devices, in Machine Hall uses Leica and in Vicon Room an OptiTrack. For that reason the amount of poses is not the same.

Thank you so much! I have converted the groundtruh to TUM format. But when I plot the two trajectories in the same coordinate with rescale and alignment option, the evo program promopt: [ERROR] found no matching timestamps between reference and f_dataset-MH01_mono.txt with max. time diff 0.01 (s) and time offset 0.0 (s)
How can I align them since the time stamp may not be in the corresponding position?

**Comment by richard-elvira** [comment]
Check the timestamp units, perhaps one of the files has the timestamps in seconds and the other in nanoseconds.

**Comment by 254843** [comment]
Hey! I also met the problem of real pose and estimated pose timestamp. Have you solved it? @squaresoft2015

**Comment by dinarkino** [comment]
> Hey! I also met the problem of real pose and estimated pose timestamp. Have you solved it? @squaresoft2015

Hey, I solved the problem by using an advice from [here](https://github.com/MichaelGrupp/evo/issues/12). You should do something like that with an estimated pose with the help of evo package or manually.

```
from evo.tools import file_interface

traj = file_interface.read_tum_trajectory_file("vins_V102.txt")

traj.timestamps = traj.timestamps / 1e9

file_interface.write_tum_trajectory_file("vins_V102_clean.txt", traj)
```

**Comment by jdtardos** [comment]
Pleas, check version v1.0
