### ISSUE TITLE
Is there a way of notifying that a loop closure has been performed?

### ISSUE THREAD

**Issue by ghost** [UZ-SLAMLab/ORB_SLAM3#747]
First of all, thank you all for bringing orb-slam3; it works wonderfully for my environment.

With that said i would like to ask if there is a way of notifying the completion of a loop closure.

I've tried keeping track of the variable mLastLoopKFid of the LoopClosing class, but it doesn't seem to change in spite of obvious loop closures.

Any way of notifying a new loop closure would suffice.

Any help would be appreciated!

**Comment by Mechazo11** [comment]
@wjdghksdl26 I was able to inform that the calculations for a loop closure was completed by printing out a message from the `void LoopClosing::CorrectLoop()` method in the LoopClosing.cc

**Comment by ghost** [comment]
thank you @Mechazo11, that worked for me.
