### ISSUE TITLE
Realsense D435i stuck on "Waiting for images"

### ISSUE THREAD

**Issue by hseysen** [UZ-SLAMLab/ORB_SLAM3#757]
I'm attempting to run the ROS version of ORB_SLAM3, and I want to test it in real-time using my Realsense D435i camera. I've not changed the Monocular-Inertial .yaml file of the camera calibration, since I assume it would be more or less similar (Although I'm not entirely sure if my camera is producing frames at 640x480 or not).

I've run the ros camera in one terminal using the following command:
```bash
roslaunch realsense2_camera rs_camera.launch unite_imu_method:=copy
```

The last option allowed me to combine accelerometer and gyroscope into one topic called `/camera/imu`, which I made sure to subscribe to in the `ros_mono_inertial.cc` file.

```c++
  // Maximum delay, 5 seconds
  ros::Subscriber sub_imu = n.subscribe("/camera/imu", 100, &ImuGrabber::GrabImu, &imugb); 
  ros::Subscriber sub_img0 = n.subscribe("/camera/color/image_raw", 15, &ImageGrabber::GrabImage,&igb);
```

Next, I ran this command on another terminal to start ORB_SLAM3 ROS:
```bash
rosrun ORB_SLAM3 Mono_Inertial Vocabulary/ORBvoc.txt Examples/Monocular-Inertial/RealSense_D435i.yaml false
```

And here I am stuck at "Waiting for images", and I just can't seem to find the source of the problem. I've opened another terminal to run `rqt_graph`, which shows me that `/Mono_Inertial` has successfully subscribed to the relevant topics:
![rosgraph](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/43686068/1f22ab7a-1d3c-48c9-a459-9779e1d9b81c)

How could I approach the solution on this? Perhaps the resolution is really not 640x480 in my case (according to [this answer](https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/501#issuecomment-1057448236) that was the root cause of their problem). I'm still new at ROS, so I would appreciate any help

Edit: I've confirmed that the resolution is set to 640x480 from the RealSense camera's roslaunch logs:
```
[ INFO] [1684922036.983369213]: Device Name: Intel RealSense D435I
[ INFO] [1684922036.983655932]: Device Serial No:
[ INFO] [1684922036.984006396]: Device physical port: 1-2.3-5
[ INFO] [1684922036.984309532]: Device FW version: 05.13.00.50
[ INFO] [1684922036.984631580]: Device Product ID:
[ INFO] [1684922036.984923868]: Enable PointCloud: Off
[ INFO] [1684922036.985264091]: Align Depth: Off
[ INFO] [1684922036.985605435]: Sync Mode: Off
[ INFO] [1684922036.985978651]: Device Sensors: 
[ INFO] [1684922037.090182329]: Stereo Module was found.
[ INFO] [1684922037.135498205]: RGB Camera was found.
[ INFO] [1684922037.137025340]: Motion Module was found.
[ INFO] [1684922037.137601243]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1684922037.137811227]: num_filters: 0
[ INFO] [1684922037.138189339]: Setting Dynamic reconfig parameters.
[ INFO] [1684922041.162527334]: Done Setting Dynamic reconfig parameters.
[ INFO] [1684922041.164656644]: depth stream is enabled - width: 640, height: 480, fps: 15, Format: Z16
[ INFO] [1684922041.166347139]: color stream is enabled - width: 640, height: 480, fps: 15, Format: RGB8
[ INFO] [1684922041.166554147]: gyro stream is enabled - fps: 200
[ INFO] [1684922041.166737667]: accel stream is enabled - fps: 100
[ INFO] [1684922041.166830083]: setupPublishers...
[ INFO] [1684922041.180082491]: Expected frequency for depth = 15.00000
[ INFO] [1684922041.195347569]: Expected frequency for color = 15.00000
[ INFO] [1684922041.207732745]: Start publisher IMU
[ INFO] [1684922041.212906310]: setupStreams...
```

**Comment by hseysen** [comment]
I also suspect that the OpenCV versions may be conflicting for some reason, due to the following terminal output when running `build_ros.sh`:

```
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.4.1
/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_imgproc.so.4.1
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, may conflict with libopencv_core.so.4.1
```

**Comment by horry0314** [comment]
Excuse me. Have you figured out this problem? I have the same problem.

**Comment by wengchenyang1** [comment]
I think the issue might be related to either `StereoInitialization()` or `MonocularInitialization()` (in `Tracking.cc`).

If the failure of the initialization is vision related, possible solutions might be moving the camera to scenes with more feature points when the program starts. Also, because of the "Waiting for images" issue, we can not check the quality of the captured image (e.g., maybe exposure is too low), so we may use opencv to show the image before sending it to SLAM. Another quick check is to reduce the values of 
```
ORBextractor.iniThFAST
ORBextractor.minThFAST
```
in the config file and see if it helps.

**Comment by hseysen** [comment]
After having wasted so much time on trying different things, I decided to recalibrate the RealSense D435i camera, and to my surprise, the `.bag` file that I recorded for Kalibr did not pick up the `/camera/imu` topic. I assume this was a hardware failure, and will move on to fusing my own camera and imu.
