### ISSUE TITLE
Camera IMU time offset

### ISSUE THREAD

**Issue by rmvanarse** [UZ-SLAMLab/ORB_SLAM3#78]
Hello, thank you for this work
I am using the system with my own stereo camera + IMU setup. I have the value of ```timeshift_cam_imu``` in my calibration yaml file from kalibr. Where can I set this value in ORB_SLAM3?

**Comment by karnikram** [comment]
I have the same issue. It seems like they assume through out their system that no time-offset exists between the sensors i.e. the sensors are hardware triggered to capture measurements at the same time.

**Comment by richard-elvira** [comment]
Our system assumes that each IMU measurement and frames have their own timestamp. An IMU sensor has several measurements between two frames, for that reason, it is necessary to provide all the inertia measurements between the last frame and the current one, if there is an offset in the IMU timestamp you can add it to the IMU timestamp to get actual measurement timestamp.
