### ISSUE TITLE
Can ORB-SLAM3 be used for RGB-D multi-robot SLAM? 

### ISSUE THREAD

**Issue by TwiceMao** [UZ-SLAMLab/ORB_SLAM3#791]
Can ORB-SLAM3 be used for RGB-D multi-robot SLAM? Now I have separate RGB-D data of two robot trajectories. I want to get the pose estimation results under multi-machine SLAM. Can you provide sample code? I have no experience with ORB-SLAM3, can you help me? thank you!

**Comment by Mechazo11** [comment]
In theory you can use ROS to use the two separate datasets but ORB SLAM3 by default is written for a single agent system. You will have to modify it considerably to make it work in a multi-agent system

Updated: 09/12/23
