### ISSUE TITLE
Confused with openCV version

### ISSUE THREAD

**Issue by snowWork1234** [UZ-SLAMLab/ORB_SLAM3#799]
In the readme file, it said that: _Required at least 3.0. Tested with OpenCV 3.2.0 and 4.4.0._. However, in the CMakeLists.txt, it only find OpenCV 4.4.0, otherwise it will print error messages. Hopefully the authors can go through the whole repository and fix such problems. ORBSLAM3 would be perfect without these problems.

**Comment by geoeo** [comment]
try to change the version the CMAKE. This can happen in opensource software. Someone bumped the version and didnt change the readme
