### ISSUE TITLE
Why are ORB features calculated explicitly instead of using OpenCV

### ISSUE THREAD

**Issue by geoeo** [UZ-SLAMLab/ORB_SLAM3#800]
Hello,

I was wondering behind the rationale of calculating ORB features explicitly instead of using the black boxed opencv version.
Using the OpenCV version would allow for CUDA access, or were the experiences with OpenCV ORB bad?

**Comment by Userpc1010** [comment]
A similar question was asked earlier in [stella vslam](https://github.com/stella-cv/stella_vslam/discussions/414#discussion-4530163) (OpenVSlam) based on ORB-SLAM 2, apparently one of the reasons was the distribution of points in the image and their number.

**Comment by geoeo** [comment]
Ok so its because of the sampling pattern. I guess the ORB one is different than the one hardcoded in opencv

**Comment by Userpc1010** [comment]
In any case, the ORB looks outdated, perhaps the best solution would be [NCNN](https://github.com/KinglittleQ/SuperPoint_SLAM) detectors.
