### ISSUE TITLE
Is there the possibility to deactivate Loop Closure and/or Multimapping?

### ISSUE THREAD

**Issue by ylenianistico** [UZ-SLAMLab/ORB_SLAM3#802]
Hi all, 
I am using ORB-SLAM3 with my own dataset. I would like to check the performance without loop closure and/or multi-mapping.
Is there a way to do it easily?

**Comment by Mechazo11** [comment]
@ylenianistico Yes both are controlled by two boolean variables in the LoopClosing.cc. These should be the `mbLoopDetected` and the `mbMergeDetected` variables. Both are set in the  `bool LoopClosing::NewDetectCommonRegions()` method.
