### ISSUE TITLE
Can't run ORB_SLAM3 

### ISSUE THREAD

**Issue by IAMHAADICOOL** [UZ-SLAMLab/ORB_SLAM3#821]
The library built successfully with the help of ./build.sh command
Now when I trying to run it using the following command
./Examples/Stereo-Inertial/stereo_inertial_realsense_D435i Vocabulary/ORBvoc.txt ./Examples/Stereo-Inertial/RealSense_D435i.yaml
I am getting the following error./Examples/Stereo-Inertial/stereo_inertial_realsense_D435i Vocabulary/ORBvoc.txt ./Examples/Stereo-Inertial/RealSense_D435i.yaml
![Screenshot from 2023-10-18 12-04-07](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/99788862/f93999b4-f57e-445e-8af4-d859dc87ec0b)
I have connected the Realsense camera successfully, I am not able to understand why is it happening.
Can someone help me out please?

**Comment by CurlyWei** [comment]
Hi bro,you execute the .cc file(show terminal pic).
You should execute the exe file

**Comment by IAMHAADICOOL** [comment]
I can't find the exe file after building

**Comment by CurlyWei** [comment]
1.Can you show or check your document(ORB_SLAM3/Example/Stereo-Inertial/stereo_inertial_realsense_D435i) ?
2.make sure your build.sh is successful ?

**Comment by IAMHAADICOOL** [comment]
Yeah, I checked it😅
And yeah, I built it three times, it build successfully
There is just cc file in the mentioned location of yours😅

**Comment by CurlyWei** [comment]
Did you have install realsense?
Check  line 213 in the CMakeLists.txt.
If you didn`t have it,
the exe can`t be built it

**Comment by IAMHAADICOOL** [comment]
Oh yeah, maybe that is the case, I'll built Realsense and then respond back
to you, thanks, I'll surely respond back.
