### ISSUE TITLE
Build error make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/ORB_SLAM3.dir/all] Error 2

### ISSUE THREAD

**Issue by kenhuang1964** [UZ-SLAMLab/ORB_SLAM3#834]
Did anyone come across this error while building? Any idea on how to resolve this issue? 

make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/ORB_SLAM3.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by jeremy7703** [comment]
How do you solved this issue?
