### ISSUE TITLE
OAK-D Pro

### ISSUE THREAD

**Issue by kenhuang1964** [UZ-SLAMLab/ORB_SLAM3#837]
Anyone tried ORB-SLAM3 with OAK-D Pro? Does it work well?

**Comment by mkarklins** [comment]
It didn't work "well", but it worked : )
For me personally the orbslam3 process kept getting stuck/unresponsive after some time, but I don't think it's directly related to the camera model.

I followed this tutorial - https://qiita.com/nindanaoto/items/20858eca08aad90b5bab

**Comment by kenhuang1964** [comment]
Thanks @mkarklins!
