### ISSUE TITLE
the application crash when using custom stereo camera. segment fault(core dump)

### ISSUE THREAD

**Issue by zhOrange** [UZ-SLAMLab/ORB_SLAM3#86]
crash message:
`New Map created with 42 points
segment fault(core dump)
`
Does anybody get this problem?
I find some solution from [https://github.com/raulmur/ORB_SLAM2/issues/341](url).
But it didn't work to me.

**Comment by jjgr3496** [comment]
I would need more information to track down the error. Please, try to find in which line the program crashes. However, at a first glance, this sounds to me that you have compiled g2o and OR-SLAM3 libraries with different compilers (or different versions of the same one) so please, double check that you compile everything with the exact same compiler (and version!).
