### ISSUE TITLE
Tracking lost when running stereo/mono mode in EuRoC dataset

### ISSUE THREAD

**Issue by ananyaverma2** [UZ-SLAMLab/ORB_SLAM3#863]
I am getting the following error "Fail to track local map" while running stereo_euroc. I tried changing the ORB parameters in the yaml file, but it doesn't seem to work.
![Screenshot from 2024-02-01 09-09-52](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/77563519/107c7383-f1a7-46b0-833e-2245c5ff48ae)

**Comment by ananyaverma2** [comment]
Tweaking the parameters solved the issue.

**Comment by MacintoshChen** [comment]
Hello, may I ask which parameters have you changed? I'm running into a similar issue.

**Comment by ananyaverma2** [comment]
I changed a few of them but the ones that affected the tracking the most were to increase the number of features detected and decrease the threshold of ORBmatcher.

**Comment by ashwinjosephk** [comment]
Hey @ananyaverma2 , I have an issue with getting the example mentioned on the git page with the EuRoC dataset working,
I was following the [tutorial](https://github.com/UZ-SLAMLab/ORB_SLAM3?tab=readme-ov-file) and was able to build using ./build_ros.sh on Ubuntu 20.04LTS having ROS Noetic.
As per the tutorial the next step is a rosrun command like 'rosrun ORB_SLAM3 Mono PATH_TO_VOCABULARY PATH_TO_SETTINGS_FILE'
I then tried the EuRoC example command:
rosrun ORB_SLAM3 Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/EuRoC.yaml true
but executing it gives me the error "[rosrun] Couldn't find executable named Stereo_Inertial below /home/knnas/catkin_ws/src/ORB_SLAM3/Examples_old/ROS/ORB_SLAM3" I don't really know why it is searching in the Examples_old folder =, can you give me any leads on what am I doing wrong here?
![image](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/30999857/d9594712-7cfe-4ce6-ab5e-aef1802f26e6)

and if I manage to get the path right, I get another error:
![image](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/30999857/2869b089-293e-4b18-98c1-98571e5db976)
