### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by zhengweiSRC** [UZ-SLAMLab/ORB_SLAM3#91]
when I run with the command "rosrun ORB_SLAM3 Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/EuRoC.yaml true"
I find the following problem 
"
OpenCV Error: Assertion failed (0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows) in Mat, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp, line 483
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp:483: error: (-215) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function Mat
"

**Comment by jjgr3496** [comment]
I would need more information in order to help you. Could you please find in which part of the code is failing?

**Comment by zhengweiSRC** [comment]
I am

> I would need more information in order to help you. Could you please find in which part of the code is failing?
