### ISSUE TITLE
Issue finding the executable file 

### ISSUE THREAD

**Issue by ashwinjosephk** [UZ-SLAMLab/ORB_SLAM3#914]
I was following the [tutorial](https://github.com/UZ-SLAMLab/ORB_SLAM3?tab=readme-ov-file) and was able to build using `./build_ros.sh` on  Ubuntu 20.04LTS having ROS Noetic.
As per the tutorial the next step is a rosrun command like `'rosrun ORB_SLAM3 Mono PATH_TO_VOCABULARY PATH_TO_SETTINGS_FILE'`
I then tried the EuRoC example command:
`rosrun ORB_SLAM3 Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/EuRoC.yaml true`
but executing it gives me the error _"[rosrun] Couldn't find executable named Stereo_Inertial below /home/knnas/catkin_ws/src/ORB_SLAM3/Examples_old/ROS/ORB_SLAM3"_ I don't really know why it is searching in the Examples_old folder and why the example ain't working as suggested in the tuorial, can anyone help me understand the issue here?

![image](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/30999857/d9594712-7cfe-4ce6-ab5e-aef1802f26e6)

and if I manage to get the path right, I get another error:
![image](https://github.com/UZ-SLAMLab/ORB_SLAM3/assets/30999857/2869b089-293e-4b18-98c1-98571e5db976)

**Comment by khshmt** [comment]
executables of the ROS nodes exist in "Examples_old" not in "Examples", what in "Examples" are CPP executables not ROS nodes
