### ISSUE TITLE
When using fisheye, UndistortKeyPoints() dose not work

### ISSUE THREAD

**Issue by Richard-coder** [UZ-SLAMLab/ORB_SLAM3#95]
I run orb-slam3 on TUM-VI dataset，in function Frame::Undistortkeypoints(), because mDistCoef.at<float>(0)=0, mvKeysUn=mvKeys,  UndistortKeyPoints() actually dose not work. Is this normal?

I am not familiar with fish-eye camera, and I am trying to learn fish-eye SLAM.

Thank you

**Comment by richard-elvira** [comment]
Yes, in the fisheye case the system works with the distorted image. The class KannalaBrandt8 has the distortion parameters to calculate the undistort point. That class can show you how the system works with fisheye cameras.

**Comment by Richard-coder** [comment]
@richard-elvira ，Thank you for your reply
