### ISSUE TITLE
How did you create the setting files?

### ISSUE THREAD

**Issue by choffmann** [UZ-SLAMLab/ORB_SLAM3#99]
Did you create those by hand or used any tool? Using pyyaml and `FileStorage` from Opencv results in a not very nicely ordered file. Also `FileStorage` does not allow Dot in the key. So `camera.fx` is not allowed.

**Comment by jjgr3496** [comment]
We hand-crafted them as the calibration provided by every dataset creator follows a different format. We have inherited the style for the calibration files from ORB-SLAM and ORB-SLAM2.

**Comment by choffmann** [comment]
Ok, thx.
